### ISSUE TITLE
Cannot Delete Backups

### ISSUE THREAD

**Issue by Abys5** [wisp-gg/frontend#1]
**Describe the bug**
When deleting Backups it 404 errors

**To Reproduce**
Just attempting to delete any backup, no steps required.

**Expected behavior**
To delete the backup

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Brave

**Additional context**

**Comment by 0xCiBeR** [comment]
This is still not fixed for me, getting a 404 when deleting a backup
