### ISSUE TITLE
Missing: Page to create announcements

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/frontend#100]
**Describe the bug**
There is no page to create new announcements.

**To Reproduce**
1. Go to Admin area
2. Look for announcements
3. See error

**Expected behavior**
I would expect to be able to create announcements

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Chrome
Version: 98.0.4758.82

**Comment by victiondev** [comment]
fixed in next release
