### ISSUE TITLE
Incorrect announcements shown.

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/frontend#102]
**Describe the bug**
Panel is showing a random announcement from someone else for everyone instead of their own.

**To Reproduce**
1. Click on View Announcements
2. See error

**Expected behavior**
I expect my announcements to be shown, not someone else.

**Screenshots**
![image](https://user-images.githubusercontent.com/61161558/153779032-b023acc1-3394-4222-9db2-b469ed0d9a79.png)

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Chrome
Version: 98.0.4758.82

**Comment by krenny** [comment]
I can't even view any announcement xD

![grafik](https://user-images.githubusercontent.com/77990771/153779569-0aa4064c-8931-48b8-aa69-578379fea3db.png)

**Comment by bastienroussel** [comment]
Fix in lastest release (v.2.0.26)
