### ISSUE TITLE
Suspended servers report no permissions even in admin area

### ISSUE THREAD

**Issue by krenny** [wisp-gg/frontend#103]
**Describe the bug**
If you visit a suspended server the error `You do not have permission to access the websocket for this server.` appears, which is a bit misleading since it is suspended and the "Server suspended" Page should appear.
However this even aplies if a admin visits the server in the admin area.

**To Reproduce**
1. suspend a server
2. Hit Ctrl+f5
3. See error

**Expected behavior**
Users should get the suspended page, while admins shouldn't get any error.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/77990771/153780956-b0b1fb34-e94d-4cd5-942a-bfc9a39d511f.png)

**Additional context**
Note: It also shows error as status instead of suspended

Note2: This is only a visual bug the function seem to be working fine.
Users can't manage their servers via panel and api.
Admins can manage the server via panel and api.
and the server gets killed when it gets suspended

**Comment by WISPdotGG** [comment]
Reproduced

**Comment by larsjarred9** [comment]
I would like to add to this issue that the server statistics are showing the service online with wrong statistics for a suspended service in my case
![image](https://user-images.githubusercontent.com/31996561/154139366-40e7d53b-7f88-4dd1-8df5-a33fed222297.png)
