### ISSUE TITLE
Last Admin should not be able to remove his admin permissions

### ISSUE THREAD

**Issue by krenny** [wisp-gg/frontend#106]
**Describe the bug**
The last user can update his own User profile and remove his admin permissions.

**To Reproduce**
1. Go to 'Management>Users'
2. Remove your own admin perms
3. The panel has no admins anymore and is basically not useable anymore.

**Expected behavior**
There should be a protection against this layer 8 issue.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/77990771/153782781-362a9612-8d83-4c03-ab0a-6e6a029693e7.png)

**Comment by victiondev** [comment]
fixed in next release
