### ISSUE TITLE
Startup Command visual bug

### ISSUE THREAD

**Issue by Lunaversitay** [wisp-gg/frontend#108]
**Describe the bug**
Viewing the startup command in the startup parameters tab it looks like it duplicates the parameters its suppose to echo in the input field, looks to just be a visual bug, the server doesn't actually startup with them.

**To Reproduce**
1. Go to Startup Parameters

**Expected behavior**
These parameters (`{{example| -}}`) shouldn't be showing at least after the startup parameters are edited at least once but they don't seem to go away and are always at the end of the actual startup parameters.

**Screenshots**
![](https://i.lunaversity.dev/firefox_q7lZKjLhEY.png)

**Comment by victiondev** [comment]
fixed in next release
