### ISSUE TITLE
per_page variable is not working as intended

### ISSUE THREAD

**Issue by 0xCiBeR** [wisp-gg/frontend#110]
**Describe the bug**
Calling the API using per_page GET variable is not working as intended. It is forced to 50 results even if you specify something like this:
`{base_url}/api/application/nodes/18/allocations?per_page=500`

This is a needed parameter to avoid Rate Limits on high allocation hosts calling the same endpoint recursively to get allocations. Imagine for a 1000 port allocated node, it would have to call this endpoint 20 times just to get all allocations.

**To Reproduce**
1. Use the API to obtain allocations for a host using the per_page variable to something like 500

**Expected behavior**
Return the requested per_page value or at least set a higher default value to something like 500

**Additional context**
Output when setting per_page to 500:
https://www.toptal.com/developers/hastebin/alesedujaq.php

**Comment by 0xCiBeR** [comment]
Yes, but 50 is a very low limit. Like I said, you would have to make 20 requests to get a 1000 port allocated node results.

**Comment by WISPdotGG** [comment]
We should be able to raise this to 250 at least

**Comment by TrixterTheTux** [comment]
Should be bumped to default to 100 with the ability to set it up to 250 in the next update.
