### ISSUE TITLE
Backup toggle does not work for stuck backups

### ISSUE THREAD

**Issue by Lunaversitay** [wisp-gg/frontend#112]
**Describe the bug**
When a backup gets stuck usually just toggle backup to fix it, but it seems like the backup doesn't show despite the server being stuck on backing up status.

**To Reproduce**
1. Somehow get the backup to freeze on creating
2. Go to admin page and look at toggle backups

**Expected behavior**
If a backup is in progress it should show up in the backup toggle list in the admin area.

**Screenshots**
![](https://i.lunaversity.dev/firefox_WKMiptv47t.png)
![](https://i.lunaversity.dev/firefox_FYLQut6puo.png)

**Comment by desperadisse** [comment]
+1 Same error for one client

**Comment by victiondev** [comment]
this is done - forgot to close

**Comment by OneHitX** [comment]
Can this be reopened? I had the same problem today. @victiondev
