### ISSUE TITLE
Ability to open link in a new tab

### ISSUE THREAD

**Issue by bgbuddyboy** [wisp-gg/frontend#115]
**Describe the bug**
Due to page loading being redone in v2, links are now buttons which means pages cannot be opened in a new tab without duplication or a new tab all together.

**To Reproduce**
Definitely occurs on:
- Admin Nodes
- Admin Servers
- Admin Users
- Admin DBs
- Admin Nests
- Admin Mods

**Expected behavior**
Ability to open pages in a new tab

**Screenshots**
N/A

**Additional context**
N/A

**Comment by SkyMulley** [comment]
Also occurs on any File Management with directories, had a person feature req this

**Comment by krenny** [comment]
Same thing for the logo
Clicking the logo with a normal left-click opens the user are.
Clicking it with a the wheel(new tab) opens the cdn where the picture is stored….

**Comment by TrixterTheTux** [comment]
Is this still an issue? Holding ctrl+clicking URL opens the correct URL which used to be the CDN url due to a bug, so I assume this is now fixed?

**Comment by bgbuddyboy** [comment]
Forgot to reply.

Yes, this is still occurring for the admin side.
