### ISSUE TITLE
File Management Rename Error

### ISSUE THREAD

**Issue by SkyMulley** [wisp-gg/frontend#116]
**Describe the bug**
Attempting to rename files/folders in File Management causes an error and fails

**Screenshots**
![image](https://user-images.githubusercontent.com/22577275/153813257-a3396b62-bdad-4f27-a07c-69e895de7a49.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version Latest Stable

**Additional context**
![image](https://user-images.githubusercontent.com/22577275/153813380-70734e8f-2161-4488-b83c-58a1e8ae6acc.png)

**Comment by TheIntolerant** [comment]
Since "rename" and "move" come under the same button, I will just add to this issue.
It also seems you cannot move files as well as rename them.

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.

**Comment by TheIntolerant** [comment]
The error is no longer coming up, however, it still seems like we are unable to rename/move files/folders.
