### ISSUE TITLE
/api/application/nodes/<node-id>/allocations doesnt respond to page=X argument

### ISSUE THREAD

**Issue by 0xCiBeR** [wisp-gg/frontend#117]
**Describe the bug**
I was debuging why my pterobill module was not working, and to try i wanted to reduce total allocations on my node. For this i called the `/api/application/nodes/<node-id>/allocations` endpoint to get allocation ids, and found that even though you set page=X it always gives you page 1, so there is something wrong with pagination

**To Reproduce**
1. Call the `/api/application/nodes/<node-id>/allocations` endpoint specifying a page number other than 1
2. Page 1 is always displayed

**Expected behavior**
Pagination should give me the page number i ask in url

**Screenshots**
![image](https://user-images.githubusercontent.com/9750850/153830709-2b9f0808-fd3f-407f-8dae-44de6a5c4893.png)

**Additional context**
Maybe related to #85 and #110

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.

**Comment by 0xCiBeR** [comment]
I can confirm this was fixed. Thanks
