### ISSUE TITLE
Error when clearing announcements

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/frontend#118]
**Describe the bug**
When trying to clear announcement, the error "Something went wrong while trying to perform this action." gets displayed.

**To Reproduce**
1. Go to any page
2. Click on client announcements
3. Click clear all

**Expected behavior**
I expect to be able to clear announcements

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Chrome
Version: 98.0.4758.82

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.
