### ISSUE TITLE
Ads on other panels

### ISSUE THREAD

**Issue by Indygen** [wisp-gg/frontend#119]
**Describe the bug**
When you create an ad on the panel, it doesn't show your ad at all. When you close the panel tab and re-enter the panel, there is a message from another panel.

**To Reproduce**
1. Go to Settings
2. Click on Announcements
3. Click on "Create" and select type and write content
4. Close browser or tab
5.  Rejoin on panel and check Announces

**Expected behavior**
Normally the ads I added should be displayed.

**Comment by bastienroussel** [comment]
Fix in lastest release (v2.0.26)
