### ISSUE TITLE
Unmigrated Node Servers show in list

### ISSUE THREAD

**Issue by larsjarred9** [wisp-gg/frontend#120]
**Describe the bug**

**To Reproduce**
1. Have unmigrated node
2. Head over to server list
3. Find unmigrated server

**Expected behavior**

I expect it to show a yellow dot (pending migration) or not show in the users server list

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 PRO
 - Browser: Opera (Chromium)
 - Version: v2.0.26

![image](https://user-images.githubusercontent.com/31996561/153859448-337e29e5-0693-45a3-88fe-2414911604be.png)

**Comment by bastienroussel** [comment]
Seems to be related to issue #9

**Comment by larsjarred9** [comment]
Not same issue as #9 is related to websockets whilst my issue is related to how unmigrated servers (from node that does not exist) are displayed. Since they used to display an error msg in yellow if I am not mistaken.

**Comment by sharletp** [comment]
It seems that this issue has been resolved by a latest version release. @WISPdotGG 

**Screenshots**
![Screenshot from 2022-02-16 02-55-33](https://user-images.githubusercontent.com/24799477/154169885-1af6b2d1-9ab0-42be-94d2-b089e8b55436.png)

**Desktop**
- **OS**: Ubuntu 20.10 Desktop (Linux Distribution)
- **Browser**: Chrome 96.0.4664.110 (Official Build) (64-bit)
- **Version**: v2.0.36
