### ISSUE TITLE
Minecraft servers do now show mods tab

### ISSUE THREAD

**Issue by krenny** [wisp-gg/frontend#122]
**Describe the bug**
Minecraft eggs shows now Mods under Tools.

**To Reproduce**
1. Go to create a minecraft server.
2. Open the server via user view and look at Tools tab

**Expected behavior**
Not sure if that's a bug but since it wasn't there in v1 I am assuming it shouldn't be there.

**Screenshots**
![image](https://user-images.githubusercontent.com/77990771/153864485-f61fc854-ca49-4655-a862-cde4035b7220.png)

**Comment by TrixterTheTux** [comment]
Isn't a bug but is also now hidden by default if there are no mods (#159).
