### ISSUE TITLE
Minecraft Plugins pagination is broken

### ISSUE THREAD

**Issue by krenny** [wisp-gg/frontend#123]
**Describe the bug**
This might be a duplicate, I think I already saw this bug but can't find it so opening a new one
The Plugin pagination is broken, if you go too far the panel can't load any plugins.

**To Reproduce**
1. Create minecreaft server
2. Go to Plugin Manager
3. Go to last page
4. see error

**Expected behavior**
either limit the pages or fix this bug

**Screenshots**
![image](https://user-images.githubusercontent.com/77990771/153865663-cc5b1533-2638-4bbc-9088-34d8afbe28ba.png)

**Comment by TrixterTheTux** [comment]
Should be limited to 10 pages in the next release until we get our custom solution working.
