### ISSUE TITLE
about cmd console freezing

### ISSUE THREAD

**Issue by cengizhanbucak** [wisp-gg/frontend#124]
When we leave the console cmd tab open and come back after a certain period of time, the cmd page freezes, sometimes it takes a long time to come to it, sometimes it does not come, we have to renew it.

1- For example, open the cmd page of the rust server, then switch to the side tab and wait for some time.
2- When you return, you will notice that the cmd console does not accept commands and freezes.

It should be updated in the background from where it always left off, and the command should be ready to be used as soon as it returns.

**Desktop**
 - OS: [Windows 10]
 - Browser chrome

**Comment by craig-g** [comment]
I think its the graphs, i removed the graphs and no longer have any issues with my tab crashing/lagging/being generally unresponsive.

**Comment by TrixterTheTux** [comment]
Would any of you be able to get a performance/memory dump from the profilers found in the developer console's tabs (right click page, inspect element, memory/performance tabs) on Chrome when you're experiencing this issue?
