### ISSUE TITLE
Database Link

### ISSUE THREAD

**Issue by bastienroussel** [wisp-gg/frontend#125]
**Describe the bug**
Normally there is a way to link a database hosts to an node. Actually this option doesn't appear and all my customers on a specific node cannot create a new database and the creation with the admin side doesn't work too.

**Screenshots**
![image](https://user-images.githubusercontent.com/52447846/153884187-89e007ec-060e-4228-9019-8a7298811728.png)

**Comment by victiondev** [comment]
fixed in latest release
