### ISSUE TITLE
Client api key ip input render glitch

### ISSUE THREAD

**Issue by DarthShmev** [wisp-gg/frontend#136]
**Describe the bug**
When typing in any characters into the allowed ip field, the displayed text value looks really odd.

**To Reproduce**
1. Go to My Account -> Security Controls
2. Click on Create
3. Type anything into the allowed ips field

**Expected behavior**
The displayed text should render properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/34663790/153982297-5f63b4bd-cf57-4d51-890b-726fae35ba54.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser: Chrome

**Comment by sharletp** [comment]
Confirmed, can reproduce 👍🏻 
I can try to select the input from the dropdown menu and it does seem to work and so is the case for the rest of them however as you had mentioned the weird "dashed lines" or so do appear.

**Screenshots**
![Peek 2022-02-15 12-34](https://user-images.githubusercontent.com/24799477/154035526-3f55d524-9ee6-4e48-b3d1-2a63712e37f4.gif)

**Desktop**
- **OS**: Ubuntu 20.10 Desktop (Linux Distribution)
- **Browser**: Chrome 96.0.4664.110 (Official Build) (64-bit)
- **Version**: v2.0.32

**Comment by Software-Noob** [comment]
For more information: This affects everything using the multi-select library, e.g, node allocations

**Comment by victiondev** [comment]
cant reproduce this on firefox or chrome on macos (don't have access to windows atm)


<img width="317" alt="image" src="https://user-images.githubusercontent.com/26467584/160400744-841181dd-d472-4dcf-8361-a56d9a464722.png">
<img width="353" alt="image" src="https://user-images.githubusercontent.com/26467584/160400711-48d75106-f3a4-46cd-825b-c226e6494d31.png">

**Comment by Software-Noob** [comment]
It affects everything containing multi-select. For example, allowed connection IPs and node allocations. Can reproduce on all platforms: Linux/Windows/macOS with Safari, FF, and Chrome.

![image](https://user-images.githubusercontent.com/10975908/162024733-ff73581a-a900-4ca2-92a3-625993c41e3a.png)

![image](https://user-images.githubusercontent.com/10975908/162024797-4fe1a9db-c4e0-47cc-bc3c-8ad6b4a0ce5d.png)
