### ISSUE TITLE
Incorrect user ("root") mentioned for console input.

### ISSUE THREAD

**Issue by sharletp** [wisp-gg/frontend#137]
**Describe the bug**
The console input section for all servers mentions the user in use as root.

**To Reproduce**
1.  Access an instance of the WISP Game Control Panel.
2. Either select managing the server or choose the console window method.
3. View the section detailing the user input for the console.
4. User `root` is mentioned.

**Expected behavior**
The user mentioned via the console input section must be named as `container` rather than `root` as is the case for every other service which relies on the `container` user on the panel such as the file manager, images of eggs, etc.

**Screenshots**
![Screenshot from 2022-02-15 10-12-36](https://user-images.githubusercontent.com/24799477/154012504-ba3608dd-07f1-4bb2-8770-9a9e7459a220.png)
![Screenshot from 2022-02-15 10-25-04](https://user-images.githubusercontent.com/24799477/154012718-4b6a7bd4-3575-4a2b-9e78-d31b8202a230.png)

**Desktop**
 - **OS**: Ubuntu 20.10 Desktop (Linux Distribution)
 - **Browser**: Chrome 96.0.4664.110 (Official Build) (64-bit)
 - **Version**: v2.0.32

**Additional context**
None

**Comment by WISPdotGG** [comment]
Going with root was a choice to make the console feel more like a terminal - we're going to leave it as root for now. But you will be able to modify the theme yourself to do this at some point in the near-term future I hope. As far as I'm aware this doesn't cause any actual UX issues and is just a preference thing.
