### ISSUE TITLE
Incorrect title for panel sites for specific pages.

### ISSUE THREAD

**Issue by sharletp** [wisp-gg/frontend#138]
**Describe the bug**
Some of the pages (specifically the direct console window and 404 pages) titles do not properly resolve and instead return with `navigation.404.title` and `navigation.server.console.title`.

**To Reproduce**
- Regarding the Direct Console Window..
  1. Access an instance of the WISP Game Control Panel.
  2. Choose the console window method for one of the servers.
  3. View the header of the window for the browser detailing the title as "Panel.. | navigation.server.console.title"
  
- Regarding the 404 Page..
  1. Access an instance of the WISP Game Control Panel.
  2. Modify the URL to head over to an unknown location.
  3. View the header of the window for the browser detailing the title as "Panel.. | navigation.404.title"
  
**Expected behavior**
The titles I believe must properly be injected with whatever they do reference, I am unfortunately not sure of what they were mentioned as before I suppose since it is being resolved at some point via the codebase that would be the case.

**Screenshots**
- Regarding the Direct Console Window..
![Screenshot from 2022-02-15 10-36-38](https://user-images.githubusercontent.com/24799477/154015853-992cd438-b44c-4274-bac1-ce129e38f441.png)

- Regarding the 404 page..
![sidissue](https://user-images.githubusercontent.com/24799477/154015891-fe0791d8-c931-4046-90d7-b778935acbb1.png)

**Desktop**
 - **OS**: Ubuntu 20.10 Desktop (Linux Distribution)
 - **Browser**: Chrome 96.0.4664.110 (Official Build) (64-bit)
 - **Version**: v2.0.32

**Additional context**
Primarily found and reproduced this for the direct console window and 404 pages, can't find it for anything else.

**Comment by JouanDeag** [comment]
Duplicate of #49

**Comment by sharletp** [comment]
Indeed, my apologies, will gladly close it, thank you and have a blessed one!
