### ISSUE TITLE
Input does not get accepted on mobile devices for console.

### ISSUE THREAD

**Issue by sharletp** [wisp-gg/frontend#139]
**Describe the bug**
The input field for the console does not seem to accept anything for mobile devices.

**To Reproduce**
1. Access an instance of the WISP Game Control Panel on a mobile device.
2. Manage any online server, ensure to select the console page.
3. Try to introduce an input for the console and hit enter, however the input does not get processed.

**Expected behavior**
The input field is supposed to process the "command" (or any input) through as it does on desktop.

**Screenshots**
https://user-images.githubusercontent.com/24799477/154019926-d729bc08-87d6-4dfa-b000-636225401648.mp4

**Smartphone**
 - **Device**: Honor 10 Lite (HRY-LX1)
 - **OS**: Android 10 (EMUI 10.0.0)
 - **Browser**: Chrome 98.0.4758.87
 - **Version**: v2.0.32
 
**Additional context**
None

**Comment by 0xCiBeR** [comment]
+1 I can confirm this

Device: Samsung S21 Ultra 5G
OS: Android 12 OneUI 4
Browser: Chrome

**Comment by SkyMulley** [comment]
Can't reproduce this on iOS interestingly, looks like an Android exclusive problem.

Device: iPhone XS/iPad Pro (2018)
OS: iOS 15.2.1
Browser: Firefox/Safari (works on both browsers)

**Comment by SirChopwood** [comment]
+1
Device: Samsung Galaxy S9
OS: Android 10 OneUI 2.5
Browser: Samsung Internet

Appears to simply not link the "Go" (replacing Enter) key to the pushing of the input line

**Comment by TrixterTheTux** [comment]
I don't have an Android phone to test this with, but would appreciate it if someone could check what code the "Go" button gives here: https://www.w3.org/2002/09/tests/keys.html

**Comment by JouanDeag** [comment]
> I don't have an Android phone to test this with, but would appreciate it if someone could check what code the "Go" button gives here: https://www.w3.org/2002/09/tests/keys.html

It gives 13

**Comment by sharletp** [comment]
> I don't have an Android phone to test this with, but would appreciate it if someone could check what code the "Go" button gives here: https://www.w3.org/2002/09/tests/keys.html

I can confirm that it does return **13** for me as well on Android 10 (Honor 10 Lite), below is an image as attached proof to my claims.
![Screenshot_20220220_234137](https://user-images.githubusercontent.com/24799477/154863571-2ab26d5b-9bef-49cd-99c1-6626219f85b0.jpg)

**Comment by sharletp** [comment]
Apologies though whenever pressing on "Go" it had refreshed the page (I believe as expected) which is why I had to hack my way through as per the above screenshot, though I did find a better way around this which includes more details if necessary in its entirety, here you go.
![Screenshot_20220220_234625](https://user-images.githubusercontent.com/24799477/154863718-bd4c2e1e-98aa-4de7-a982-bb9b2d6482e3.jpg)
