### ISSUE TITLE
Padding/alignment: admin area server owner column

### ISSUE THREAD

**Issue by Abys5** [wisp-gg/frontend#14]
**Describe the bug**
The Owner column content is not aligned to the left where as the rest are.

**To Reproduce**
1. Go to Admin Panel
2. Go to Management > Servers
3. See Error

**Expected behavior**
Left Aligned Owner Column

**Screenshots**
[Image](https://i.imgur.com/L1wa6db.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Brabe

**Comment by victiondev** [comment]
this has been fixed now
