### ISSUE TITLE
Sub-User permissions are not saved when no permissions are selected

### ISSUE THREAD

**Issue by mov51** [wisp-gg/frontend#141]
**Describe the bug**
When no Sub-User permissions are selected and you try to save them, your changes aren't saved and you aren't notified about it. 

**To Reproduce**
1. Create a Sub-User.
2. Grant them a few permissions and save them.
3. Open the configure permissions page for that Sub-User and deselect all permissions and save
4. Re-open the configure permissions page to find that no changes were made.

**Expected behavior**
That you'd be notified that a Sub-User has to have permissions to be saved. 

**Screenshots**
I don't know how this was handled on V1, and the only thing I could give here is the lack of a notification lol. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version v2.0.32

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.
