### ISSUE TITLE
Update does not propagate for Server Details.

### ISSUE THREAD

**Issue by sharletp** [wisp-gg/frontend#143]
**Describe the bug**
Changing details for any server via administrative privileges results in an error. (`Something went wrong while trying to perform this action.`)

**To Reproduce**
1. Access an instance of the WISP Game Control Panel and head over to the admin section.
2. Select any server and choose the "Details" tab.
3. Modify any of the values.
4. Applying the changes results in an error.

**Expected behavior**
The changes are meant to reflect across as intended when it is submitted without any errors.

**Screenshots**
Reproduction of Error on Panel:
![Peek 2022-02-15 13-43](https://user-images.githubusercontent.com/24799477/154047220-2d2c2639-b1dd-4e40-a02b-07c6e46a7714.gif)

Console Logs associated with it:
![Screenshot from 2022-02-15 13-55-35](https://user-images.githubusercontent.com/24799477/154048171-078b3bcc-6326-4499-a236-77b94b8a4354.png)

![Screenshot from 2022-02-15 13-54-07](https://user-images.githubusercontent.com/24799477/154048090-2e2b1e7f-6a75-4cdb-800e-3ef9fa2c6f82.png)

**Desktop**
 - **OS**: Ubuntu 20.10 Desktop (Linux Distribution)
 - **Browser**: Chrome 96.0.4664.110 (Official Build) (64-bit)
 - **Version**: v2.0.32

**Additional context**
- Reported by VanillyNeko#4169 on discord server for WiSP at #bugs

**Comment by arty01238** [comment]
I have the same issue! Please let us know what to do?

**Comment by sharletp** [comment]
> I have the same issue! Please let us know what to do?
I have went ahead and created a pull request #166 which aims to resolve this issue and does work as intended but the best we can do at the moment is to wait for the maintainers to have a look and if all goes well this may get merged for the next update, though nothing can be promised but they will take care of it, cheers! 😃

**Comment by victiondev** [comment]
This appears to be fixed however i still need to make a change because there's still a visual bug whicb makes the owner select box revert to the old owner after saving, once that's fixed I will close this
