### ISSUE TITLE
Resources Client API call returns invalid

### ISSUE THREAD

**Issue by SkyMulley** [wisp-gg/frontend#144]
**Describe the bug**
Resources Client API returns a webpage instead of the expected server data consistently (even if the API key used is invalid)

**Screenshots**
Uploaded logs of transaction to pastebin: https://pastebin.com/qYvyWZRz

**Desktop (please complete the following information):**
N/A (Fails on multiple applications/environments/locations)

**Comment by SkyMulley** [comment]
Issue only appears to be the resources endpoint, all other endpoints return expected data

**Comment by Physics-Dude** [comment]
Same issue here. API calls to resources (https://your-panel.com/api/client/servers/<UUID>/resources) returns the content of [index.html](https://github.com/wisp-gg/frontend/blob/ef7d6b80febc01d0def17acb419116f163fd4684/index.html)

**Comment by victiondev** [comment]
added in next release
