### ISSUE TITLE
Problem with panel

### ISSUE THREAD

**Issue by SunLight881** [wisp-gg/frontend#145]
Hi,
We have a problem with the panel and the error is: "daemon.It seems you are trying to reach a Socket.IO server in v2.x with a v3.x client, but they are not compatible (more information here: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/)"
ANd the screen: https://prnt.sc/26waxwc

**Comment by bastienroussel** [comment]
Try wisp restart on your node and check if you node has been update to v2.0.2

**Comment by WISPdotGG** [comment]
probably needs to force a daemon update by stopping wisp, deleting /var/lib/wisp/daemon/daemon.wisp, starting wisp
