### ISSUE TITLE
Deleting backups returns a 404 (malformed URL)

### ISSUE THREAD

**Issue by WISPdotGG** [wisp-gg/frontend#149]
**Describe the bug**
Can't delete backups

**To Reproduce**
1. Try to delete a backup

**Expected behavior**
The backup to successfully delete

**Recording**
[Screen recording 2022-02-15 3.58.45 PM.zip](https://github.com/wisp-gg/frontend/files/8072636/Screen.recording.2022-02-15.3.58.45.PM.zip)

**Comment by WISPdotGG** [comment]
Possibly related to #147 - the URL seems to malform in the same way

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.
