### ISSUE TITLE
Server create button misaligned

### ISSUE THREAD

**Issue by WISPdotGG** [wisp-gg/frontend#150]
**Describe the bug**
Create button in admin area looks weird

**To Reproduce**
1. Go to admin area servers page

**Screenshots**
![image](https://user-images.githubusercontent.com/72014066/154100546-cdfba2c8-fda0-4b2e-ba74-0726a90c0204.png)

**Comment by Larkify** [comment]
This is also present on users, locations, database hosts etc. Any place where it follows a similar UI layout pretty much (Search bar with create button next to it)

**Comment by victiondev** [comment]
fixed in next release
