### ISSUE TITLE
css injector

### ISSUE THREAD

**Issue by DRYXDEV** [wisp-gg/frontend#154]
Describe the bug
When using the css injector it shows an error when saving and clears the input but changes still gets made and shows.

To Reproduce

Go to Admin -> Administration -> CSS Injector
2.. Write CSS
Click Save
See error
Expected behavior
I expect to not see an error and see my CSS Code in the editor inside the panel.

Screenshots
![153763119-7c709dd7-d8ca-4baa-a417-7befcb1a1e17](https://user-images.githubusercontent.com/64630866/154109372-48280467-70c2-461a-980a-08e74e3a81eb.png)

**Comment by DarthShmev** [comment]
Duplicate of #47
