### ISSUE TITLE
Hide mod manager when empty

### ISSUE THREAD

**Issue by Larsdeijsbeer** [wisp-gg/frontend#159]
**Describe the bug**
Previously in Wisp V1 the mod manager was hidden to the users when there were no items. Now it always shows the mod manager, even when it's empty.

**Expected behavior**
Hide mod manager when there are No items to display. Now it looks confusing when there is a Modpack manager and a Mod manager which is empty.

**Screenshots**
![modmanagerwisp](https://user-images.githubusercontent.com/27996312/154146175-87e40114-30f1-4894-9e74-8ee7b28766fe.png)

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.
