### ISSUE TITLE
bedrock egg identifier not functioning as intended

### ISSUE THREAD

**Issue by giomxx** [wisp-gg/frontend#169]
**Describe the bug**

bedrock egg identifier not functioning as intended

**To Reproduce**
1. Set bedrock egg identifier to bedrock
2. Click on 'Configuration > Advanced' on a bedrock egg server
3. See that the Java version installer is still present 

**Expected behavior**

Java version installer hidden, with the reinstall option shown

**Additional context**

https://discord.com/channels/589788494524579850/591724008366538753/790669460402208829

When the feature was added in V1^

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.
