### ISSUE TITLE
setup account 404s

### ISSUE THREAD

**Issue by jozefbonnar** [wisp-gg/frontend#17]
**Describe the bug**
I have just bought wisp and when setting up the account it takes me to a 404 page this seems to be the password reset page

**To Reproduce**
1. Go to the email to setup your account
2. Click on setup your account

**Expected behavior**
It should allow me to set up a password

**Screenshots**
![image](https://user-images.githubusercontent.com/42479938/153760082-4e5390d9-c2e6-4302-afad-c348a69ec08d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave

**Comment by WISPdotGG** [comment]
"The email sent to me to reset (create) my password shows a 404, but if you just request a password reset the new link works fine"

**Comment by TrixterTheTux** [comment]
Should be fixed in next release.
