### ISSUE TITLE
Database issue on panel

### ISSUE THREAD

**Issue by albusdumbledore9** [wisp-gg/frontend#172]
**Describe the bug**
Try to make a database for a server from the admin panel

**To Reproduce**
try to make a database and it just errors with a generic error

**Expected behavior**
database doesnt get made for some reason

**Screenshots**
![image](https://user-images.githubusercontent.com/12729684/154394655-f8980131-baa5-44b6-8776-6b9721a1da6b.png)

**Desktop 
 - OS: ubuntu 20.04
 - Browser Chrome
 - Version 98.0.4758.82

**Comment by albusdumbledore9** [comment]
also extra comment, i tried restarting wisp and mariadb, still does it

**Comment by DarthShmev** [comment]
What error is outputted in console?

**Comment by DarthShmev** [comment]
Possible duplicate of #83

**Comment by albusdumbledore9** [comment]
![image](https://user-images.githubusercontent.com/12729684/154495947-f5480223-2549-4c3e-9b0a-913931f940fe.png)
![image](https://user-images.githubusercontent.com/12729684/154496006-1759cb31-a579-410d-98a3-68b770389acd.png)
![image](https://user-images.githubusercontent.com/12729684/154496060-2ea8b94e-5cd4-4f7f-acc8-989572511f2d.png)
Hi not sure if these will help

**Comment by 0xCiBeR** [comment]
I can replicate this on my instance too. I'm unable to create new database hosts with this bug

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.
