### ISSUE TITLE
Update Egg Button

### ISSUE THREAD

**Issue by ThePlay3r** [wisp-gg/frontend#174]
**Is your feature request related to a problem? Please describe.**
Back in Wisp v1, when you edited an egg, there was an "Update Egg" button, which was very handy. Unfortunately, in v2 this button is missing and only way to update an egg is by manually setting the fields.

**Describe the solution you'd like**
Preferably having the "Update Egg" button back, what it really did is it just took an `.json` of an egg and updated the values of current egg with it.

**Comment by victiondev** [comment]
This was added a while back - forgot to close.
