### ISSUE TITLE
"My Servers" showing all server statuses as "Error" when logged in as administrator

### ISSUE THREAD

**Issue by JonathanVarild** [wisp-gg/frontend#18]
**Describe the bug**
When logged in as an administrator, the status of all servers in the list shows an error. No real-time information about the server is rendered.

**To Reproduce**
1. Log in as an administrator.
2. Go to the 'My servers' tab.

**Screenshots**
![](https://i.imgur.com/lv55QNQ.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.2 (21D49)
 - Browser: Safari Version 15.3 (17612.4.9.1.5)

**Comment by TrixterTheTux** [comment]
Could you check if this still happens?

**Comment by WISPdotGG** [comment]
I can confirm this still happens

**Comment by WISPdotGG** [comment]
console logs of this happening. was intermittent in the screnshotted timeframe
![image](https://user-images.githubusercontent.com/72014066/15

Here is a longer recording of the issue happening intermittently with the console in view (not great but maybe useful)
[Screen recording 2022-02-13 9.04.16 PM.zip](https://github.com/wisp-gg/frontend/files/8056658/Screen.recording.2022-02-13.9.04.16.PM.zip)
3774948-f97a5d11-2721-40fb-a173-6f93d50c3254.png)

**Comment by lerndmina** [comment]
I'm getting this too on chrome & edge

**Comment by TrixterTheTux** [comment]
Should be fixed in next release.
