### ISSUE TITLE
Upload folder File Manager issue

### ISSUE THREAD

**Issue by Larsdeijsbeer** [wisp-gg/frontend#181]
**Describe the bug**
When uploading a folder into the File Manager all of the files get uploaded but not inside the correct folder. It puts all of the files inside of the main folder you're uploading to.

**To Reproduce**
1. Go to File Manager
2. Drag a folder from your PC into the File Manager
3. See all files but not in the correct folder

**Expected behavior**
It should create a folder with the name of the folder you are uploading and put all the files in that folder. 

**Screenshots**
![folderuploadWISP](https://user-images.githubusercontent.com/27996312/154852304-2fd8c774-ddb9-44eb-b73b-c626f89ec816.gif)

**Comment by victiondev** [comment]
Cant reproduce this on MacOS or Windows 11 - drag and dropping a folder seems to import the folder itself & its contents.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/26467584/154866067-e6b21a6f-6789-4566-ba3a-ad136dcab6bf.png">
<img width="281" alt="image" src="https://user-images.githubusercontent.com/26467584/154866071-167e3288-deaa-4d1f-b739-08f352f58281.png">
