### ISSUE TITLE
File Manager drag and drop flickering

### ISSUE THREAD

**Issue by Larsdeijsbeer** [wisp-gg/frontend#182]
**Describe the bug**
When uploading a file/folder in the file manager, the file manager drop area starts flickering.

**To Reproduce**
1. Go to File Manger
2. Drag a file on top of the File Manager
3. See behavior 

**Expected behavior**
It should show a non flickering colored area where to drop your file.

**Screenshots**

![WISPupload](https://user-images.githubusercontent.com/27996312/154852556-6b904d27-4bc4-422f-99f0-61d3619b88c0.gif)

**Desktop (please complete the following information):**
 - OS: W10
 - Browser: Chrome

**Comment by victiondev** [comment]
I can't reproduce this on MacOS or Windows 11

**Comment by WISPdotGG** [comment]
I can reproduce something similar to this on ChromeOS
