### ISSUE TITLE
Enforcing 2FA for admins enforces it for everyone

### ISSUE THREAD

**Issue by GeitJoch** [wisp-gg/frontend#19]
**Describe the bug**
If you enable 2fa for Admin Only non admins also need to enable 2fa on their account. otherwise you will get the error "The panel administrator has required you to enable 2FA for your account before being able to use the panel."

**To Reproduce**
1. Go to 'Admin section'
2. Click on 'Settings'
3. Scroll down to 'Require 2-Factor Authentication'
4. Click on 'Admin Only'
5. Save it
6. See it on a non admin account
7. See error

**Expected behavior**
Non admins doesn need to enable 2fa so see their server or manage it.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/63750846/153760204-4ca0a3eb-ba14-4f49-b53a-277101f011dd.png)
![afbeelding](https://user-images.githubusercontent.com/63750846/153760027-266eceab-a9d9-4477-8778-9404c13a6086.png)
![afbeelding](https://user-images.githubusercontent.com/63750846/153760015-4c5a2d97-d7df-45c5-996f-6e1f977d314c.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 97.0

**Comment by WISPdotGG** [comment]
Just tried this myself and it worked for me

**Comment by WISPdotGG** [comment]
I misread this issue - confirmed to be an issue

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.
