### ISSUE TITLE
Adding Allocation - Comma Separation no longer exist

### ISSUE THREAD

**Issue by falceso** [wisp-gg/frontend#196]
### Describe the bug

When trying to enter multiple port ranges in one line, the input is combined together rather than separated into individual ports ranges.

### Expected Behavior

As with V1, you would be allowed to enter `25565-25566,19132-19133` and the port range will separate into their own groups automatically rather than be considered as one line all together.

**Expected Result:**
![image](https://user-images.githubusercontent.com/10911217/155057789-bce270a4-57f4-46e8-a0fa-d99ed51d4ec7.png)

### Actual Behavior

The full input of `25565-25566,19132-19133` will be considered one group as is, no separate into different groups or even the removal of the comma.
![image](https://user-images.githubusercontent.com/10911217/155057596-4de85c34-742a-432f-a5e6-d2ae1f727e92.png)

### Steps to Reproduce

Step 1 - Visit a node you wish to add allocations onto.
Step 2 - Visit the allocation page and use the "Create New" modal.
Step 3 - Enter your Normal IP.
Step 5 - Type in `25565-25566,19132-19133` into the ports field.
Step 6 - Notice it doesn't make the port ranges separate and if you hit save, it errors as shown above.

### Browser Details

Chrome 98

### Operating System

Windows 10

### Optional additional information

```bash
Similar issue is experienced while trying to add ip ranges as well. https://i.imgur.com/3w4VUZe.png
```

**Comment by victiondev** [comment]
This is finicky to do with the select library - instead you can press enter after finishing an item to start typing the nest. This is something that may be revisted whenever we move to a new select library as planned.
