### ISSUE TITLE
Can't configure all subusers

### ISSUE THREAD

**Issue by Larsdeijsbeer** [wisp-gg/frontend#199]
### Describe the bug

After configuring the permissions via the **Configure Permissions** button it can't be used anymore.
The button can only be used once, after saving the new checked permissions the button doesn't open the menu.

### Expected Behavior

Be able to edit the permissions again after updating the permissions once.

### Actual Behavior

After updating the permissions the configure button doesn't work anymore.
![subusersissue](https://user-images.githubusercontent.com/27996312/155298618-b37bda3c-f661-4544-b3a7-573819ffda9e.gif)

### Steps to Reproduce

1. Go to a server
2. Add a couple of sub users
3. Edit the permissions and update the user
4. Try again to edit the sub user
5. See problem

### Browser Details

Chrome 98.0.4758.102 

### Operating System

Windows 10

### Optional additional information

```bash
The users are imported from the Wisp V1 migration.
```

**Comment by Larsdeijsbeer** [comment]
Sub users migrated from Wisp V1 only experience this issue.

**Comment by victiondev** [comment]
Can you show the browser console? Are there any errors in there

**Comment by Larsdeijsbeer** [comment]
![subuserissue](https://user-images.githubusercontent.com/27996312/155537481-25fc5077-f2aa-43e6-8eba-b6196d740869.gif)
[game.etheron.eu-1645710972585.log](https://github.com/wisp-gg/frontend/files/8132956/game.etheron.eu-1645710972585.log)

**Comment by victiondev** [comment]
should be fixed on next release

**Comment by victiondev** [comment]
should be fixed actually now - sorry
