### ISSUE TITLE
Popout console button shows "NoSuchKey" error

### ISSUE THREAD

**Issue by CookieMC337** [wisp-gg/frontend#2]
**Describe the bug**
When clicking on the Liveconsole an XML error occurs

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Liveconsole'
3. See error

**Screenshots**
https://i.imgur.com/Wa4MMJj.png

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version idk

**Comment by Lunaversitay** [comment]
Due to it sending you to `cdn.wisp.gg` when clicking the console popout

**Comment by victiondev** [comment]
fixed in v2.0.26
