### ISSUE TITLE
Cannot delete Processing Schedule

### ISSUE THREAD

**Issue by Larsdeijsbeer** [wisp-gg/frontend#203]
### Describe the bug

When a schedule is triggered it can't be deleted. 

### Expected Behavior

Be able to delete a schedule when processing.

### Actual Behavior

It can't be deleted while processing.

### Steps to Reproduce

![cannotdeleteschedule](https://user-images.githubusercontent.com/27996312/155536488-68714ebb-d048-4112-998b-a542ab0aded9.gif)

1. Trigger a schedule which creates a backup
2. Try to delete the schedule

### Browser Details

Chrome 98.0.4758.102 

### Operating System

Windows 10

**Comment by TrixterTheTux** [comment]
Unable to reproduce this locally and in prod environment.

**Comment by TrixterTheTux** [comment]
Deletion worked for me :v

**Comment by TrixterTheTux** [comment]
Closing due to not being able to reproduce.
