### ISSUE TITLE
Backup Schedule doesn't work

### ISSUE THREAD

**Issue by Larsdeijsbeer** [wisp-gg/frontend#204]
### Describe the bug

When creating a schedule to create a backup it doesn't create a backup and keeps processing.

### Expected Behavior

Create a backup.

### Actual Behavior

Keeps processing.

### Steps to Reproduce

1. Create a schedule which makes a backup
2. Trigger the schedule
3. Wait forever...
![backupschedule](https://user-images.githubusercontent.com/27996312/155538648-6315f34c-9c55-4b77-a2e4-987995c624ec.gif)

### Browser Details

Chrome 98.0.4758.102 

### Operating System

Windows 10

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.
