### ISSUE TITLE
Problème with the PhpMyAdmin button

### ISSUE THREAD

**Issue by KINGK0NG-V1** [wisp-gg/frontend#206]
### Describe the bug

Good evening, I would like that WISP does not add directly the continuation of /phpmyadmin/index.php but that it is with us directly to put our links so that one can really configure our phpmyadmin.

### Expected Behavior

I was expecting to be able to put my own domain name via WISP for the phpmyadmin

### Actual Behavior

This unfortunately redirected me to http://pma.hydriscloud.fr/phpmyadmin/index.php
instead of https://pma.hydriscloud.fr/

![image](https://user-images.githubusercontent.com/52496524/155622966-1975528c-4ff1-4586-b3a5-c54d9bdc3ff8.png)

### Steps to Reproduce

Step 1 - Click on management
Step 2 - Create a Database if you don't have
Step 3 - Click on PhpMyAdmin and you will be redirected 

### Browser Details

Google Chrome 98.0.4758.102

### Operating System

Windows 11

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.
