### ISSUE TITLE
Navbar CSS Injector Resets every few days

### ISSUE THREAD

**Issue by captainlights** [wisp-gg/frontend#207]
### Describe the bug

The Navbar CSS changes in code every so often, which resets the colors added via CSS injector.

.nav-primary[data-v-0ea7a9e5] {
    background: #121026;
    color: #b8b9be;
}

The "0ea7a9e5" changes, which means color no longer applies once it resets every few days.

### Expected Behavior

To work properly

### Actual Behavior

Doesn't work properly

### Steps to Reproduce

Self-explanatory explained in describe bug

### Browser Details

NA

### Operating System

NA

**Comment by TrixterTheTux** [comment]
The `data-` attributes aren't supposed to be constant as they're purely used by Vue itself for internal use on differentiating between components, nor should there really be a reason to target them explicitly.

**Comment by victiondev** [comment]
I'll be adding a data-preference tag to the nav tomorrow so you can easily target each type of nav.

The two values will be "horizontal" (top nav) and "vertical" (sidebar).

Will re-close this when added.

**Comment by victiondev** [comment]
fixed in next release
