### ISSUE TITLE
Unable to edit Startup Parameters to something null

### ISSUE THREAD

**Issue by andreblue** [wisp-gg/frontend#208]
### Describe the bug

I tried removing the workshop ID from a gmod server and it would not let me save it as null(nothing in the box, not the word null). It would display the box that it says saved
https://i.imgur.com/hPHOiEw.png
After  which if you switch pages and come back, it is set to what it was. 
https://i.imgur.com/5jE73b3.png

If you put something like -1 or 0 then it saves

### Expected Behavior

To be able to save it as null

### Actual Behavior

Says it has saved and in reality it has not.

### Steps to Reproduce

1: Go to Startup Parameters
2: Change a nullable field to null
3: Wait for the mention it is saved
4: Go to another page
5: Go back to Startup Parameters

### Browser Details

Brave Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)

### Operating System

Windows 10

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.

**Comment by andreblue** [comment]
This is still  not working. I tried it across 3 browsers(Brave, Chrome, Firefox) and it would not save it as empty

**Comment by TrixterTheTux** [comment]
I've pushed a fix that should fix this now, could you confirm if it works now? cc @victiondev

**Comment by victiondev** [comment]
can confirm its fixed
