### ISSUE TITLE
Server being Reported of being offline but displaying Player Count

### ISSUE THREAD

**Issue by Abys5** [wisp-gg/frontend#21]
**Describe the bug**
The Server that is being reported as offline (the red dot) is displaying a player count which should be possible.

**To Reproduce**
1. Go to My Server
2. See Error

**Expected behavior**
[Image](https://i.imgur.com/Jnc7sNT.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Brave

**Comment by WISPdotGG** [comment]
Related to #18
