### ISSUE TITLE
Version Changer

### ISSUE THREAD

**Issue by hoshic** [wisp-gg/frontend#23]
**Describe the bug**

**To Reproduce**
1. Go to '.../advanced

example: https://infinity.panel.gg/server/92bc163e/advanced'
2. Click on 'select any edition and version'
3. Scroll down to 'install different edition'
4. See the error

**Expected behavior**
Since the update it outputs whatever version or edition you try to install an error

"Something went wrong while trying to perform this action."

**Screenshots**
https://gyazo.com/7480a768e26022e8d4dacace53761752
https://user-images.githubusercontent.com/61242061/153767004-ffb27009-daaf-4915-9f1c-439d07ad42e5.mp4

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.
