### ISSUE TITLE
Option to enable/disable OOM killer

### ISSUE THREAD

**Issue by yesBad** [wisp-gg/frontend#234]
### Describe the feature and why you would like to see it.

Option to enable/disable OOM killer

### Describe the solution you'd like.

Option to enable/disable OOM killer

**Comment by nicholasyoannou** [comment]
It'd be great to have this, would like this to happen as well. It's been ....a real pain having to make an API request every time to update OOM -- so yea, it'd be ideal if it was on the panel, with a flip of a switch haha.
