### ISSUE TITLE
Fabric version installer installs older version of Fabric Loader for some older versions

### ISSUE THREAD

**Issue by vanjmali** [wisp-gg/frontend#236]
### Describe the bug

Using the built-in `Install Different Edition` feature in panel installs Fabric loader 0.12.12 and not the latest one for some older version of the game.

### Expected Behavior

It should install the latest Fabric Loader available, currently `0.13.3`.

### Actual Behavior

It installs Fabric Loader version `0.12.12`.

### Steps to Reproduce

Step 1 - Click on the `Configuration` and go to `Advanced` tab in navigation bar in a server
Step 2 - Go to `Install Different Edition` window and select "Fabric" as edition and select version `1.18.1`
Step 3 - Click install

### Browser Details

Version 99.0.1150.46 (Official build) (64-bit)

### Operating System

Windows 11

**Comment by TrixterTheTux** [comment]
Chances are that was the only latest available version at the time of the jar build. As I don't personally host Minecraft/Fabric server, to confirm, all of the Fabric server jars should be rebuilt when a new version of the loader is released? Why specifically is this needed?

**Comment by vanjmali** [comment]
It's not necessary. Some mods use newer versions of Fabric Loader so it happens to be required to get it to have them running. 1.18.1 is an example, it has some popular mods that require latest version.

Fabric installer installs the newest version Fabric Loader by default for all versions, I believe that should be the same with the Fabric egg's install script as well. Since we don't have a Fabric Loader selection, I think this could solve these issues and not require manual upload of installation of Fabric Loader on local PC.

**Comment by TrixterTheTux** [comment]
This should be now implemented - all of the jars are being rebuilt right now and Fabric will automatically reappear when the process finishes.
