### ISSUE TITLE
Increase Character Limit on Scheduled Commands

### ISSUE THREAD

**Issue by falceso** [wisp-gg/frontend#238]
### Describe the feature and why you would like to see it.

Our clients would like to type more than 255 characters for their scheduled commands.

An example use case provided by a client is quoted below.
> Using the scheduler as an announcement plugin and with the spacing + rgb codes to make it look nice in chat it's over 255 characters.

### Describe the solution you'd like.

Expand the character limit on scheduled commands to 512 characters.

**Comment by victiondev** [comment]
fixed in next release
