### ISSUE TITLE
Crash upon copying

### ISSUE THREAD

**Issue by Zeldaboy111** [wisp-gg/frontend#240]
### Describe the bug

When copying any text, the webpage crashes. No text is copied.
Refreshing the page does not work, closing and re-opening does.

### Expected Behavior

The text to be copied without the page crashing.

### Actual Behavior

When copying text from a file, the webpage crashes. No text is copied.
Refreshing the page does not work, closing and re-opening does.

### Steps to Reproduce

Open a panel page
Go to the File Manager
Open a file
Copy a text either by using right click -> copy or control + c

Open a panel page
Go to the console
Copy a text either by using right click -> copy or control + c

### Browser Details

Chrome  99.0.4844.84

### Operating System

Windows 10

**Comment by larsjarred9** [comment]
Can vouch for this issue +1

**Comment by TrixterTheTux** [comment]
I'm not sure if this was accidentally fixed possibly by some other commit but I'm unable to reproduce this. Is this still an issue?

**Comment by Zeldaboy111** [comment]
This issue still occurs. I am unable to copy any text from the panel (neither files nor console text).

**Comment by Software-Noob** [comment]
https://user-images.githubusercontent.com/10975908/166175278-c0169849-2be1-41b5-82a4-157ecc18b3b2.mp4


https://user-images.githubusercontent.com/10975908/166175444-7c702158-2596-4712-93e0-c32fde08805c.mp4



I can't reproduce this issue on Chrome 99 & 100 or FF 99. Have you tried using incognito mode to rule out potential extensions, or do you have a very low amount of memory on your system?

**Comment by larsjarred9** [comment]
issue seems to be resolved for me. How about you @Zeldaboy111 ?

**Comment by Zeldaboy111** [comment]
The issue is caused by the MalwareBytes browser extension as without it enabled it does work.
