### ISSUE TITLE
Changing passwords doesnt invalidate sessions

### ISSUE THREAD

**Issue by 0xCiBeR** [wisp-gg/frontend#243]
### Describe the bug

When you change your account password in the panel, it doesnt invalidate other sessions nor you have the option to close other sessions manually, creating a security risk because if an attacker can compromise an account password, even if you change it, the attacker doesn't get locked out.

### Expected Behavior

When you change your password, other sessions should be invalidated, or at least, you should be able to have the classic "Close session on other devices" option.

### Actual Behavior

You change your password and it doesn't invalidate other sessions nor give the option to close other sessions manually.

### Steps to Reproduce

1.) Sign in a device with your password
2.) Sign in another device/window with the same password
3.) Change your password
4.) Check the other session and notice you are still logged in.

### Browser Details

Chrome Version 98.0.4758.109

### Operating System

MacOS Monterey 12.2.1

**Comment by TrixterTheTux** [comment]
Should behave more consistently in the next release.

**Comment by 0xCiBeR** [comment]
@TrixterTheTux seems this is not working as intended, changing password still doesnt invalidate sessions and opens to abuse

**Comment by 0xCiBeR** [comment]
This seems to also have something to do with when you delete subusers, they dont lose access to the server they were a subuser of. Might be related

**Comment by TrixterTheTux** [comment]
Pretty sure this was already fixed (by adding invalidate sessions toggle for password changes) - if not, let me know and I'll reopen this.
