### ISSUE TITLE
Unable to Change Egg between Certain Eggs

### ISSUE THREAD

**Issue by falceso** [wisp-gg/frontend#245]
### Describe the bug

When a server is deployed with a discord bot egg _(python in this example)_, when trying to change what egg is used whether it's Python 3.10 or Discord.js, it errors out with `Something went wrong while trying to perform this action`. However, changing the egg to Minecraft for example, works perfectly fine for some. This issue is experienced on both our test instance and production.

### Expected Behavior

You are able to change the server's bot egg without any errors.

### Actual Behavior

When saving server's startup configuration to use a different bot egg, the page refreshes and shows `Something went wrong while trying to perform this action`.

### Steps to Reproduce

Step 1 - Deploy a using [Discord.py Egg](https://github.com/parkervcp/eggs/blob/master/bots/discord/discord.py/egg-discord-py-generic.json) 
Step 2 - Update the Server Configuration to use another bot egg, such as [Discord.js](https://github.com/parkervcp/eggs/blob/master/bots/discord/discord.js/egg-discord-js-generic.json).
Step 3 - Hit `Save`.
Step 4 - Discover the action fails.

https://www.youtube.com/watch?v=YARXJyWw46E
https://i.imgur.com/EQXvRG3.png

### Browser Details

Chrome 100

### Operating System

Windows 10

**Comment by TrixterTheTux** [comment]
As far as I'm aware, viction has fixed this and thus I'm closing this.
