### ISSUE TITLE
Client Auth API returns 405 error

### ISSUE THREAD

**Issue by vanjmali** [wisp-gg/frontend#246]
### Describe the bug

WISP Panel seems to wok fine, only doing API calls result in this.
`/client/auth/login` and `/client/auth/logout` return 405 error "Method not allowed" even though it should be using the correct one.

- It looks like when doing GET method on the same API, it returns 404.
- When doing POST, like it says in [the docs](https://gamepanel.notion.site/Authentication-9357aa4d7b9843128cf65923a663b972) says, it says that method is not allowed (error 405) and in headers it's mentioned it can only do GET or HEAD.
- Any other method (apart from HEAD which returns completely empty page (assuming 404)) gives 405 error but in headers it says GET, HEAD and POST are allowed.

### Expected Behavior

Returning status 200 with completed request or an actual error if any.

### Actual Behavior

Error 405 "Method not allowed" returned with odd behavior. 

### Steps to Reproduce

Attempt making an request based on the docs shown.
POST `https://your-panel.com/api/client/auth/login`

https://gamepanel.notion.site/Authentication-9357aa4d7b9843128cf65923a663b972

### Browser Details

Thunder Client

### Operating System

Windows 11

**Comment by TrixterTheTux** [comment]
Unable to reproduce:
![image](https://user-images.githubusercontent.com/10120342/162732226-ca6860be-ee65-4eab-b452-cf08f5c6a30f.png)

Though note that if you want to go through the normal user authentication workflow, you'd need to also add `Origin: https://my.panel` (and possibly initialize your session through  GET https://my.panel/sanctum/csrf-cookie endpoint).

**Comment by vanjmali** [comment]
The missing `Origin` header was the thing that was giving the 405 error. With the origin, it returns fine.
And that does makes sense. Thank you. 😄 

I do believe the wiki page should have mention it, though. I'll close the issue for now.
