### ISSUE TITLE
Reinstall toggle added to schedules tab for rust wipe

### ISSUE THREAD

**Issue by mattpursuit** [wisp-gg/frontend#248]
### Describe the feature and why you would like to see it.

I would like to see the reinstall feature as an added option into the schedule tab of the wisp panel so i can set automatic wipes for my rust servers 

### Describe the solution you'd like.

Just add Reinstall as an option to the tasks tab

**Comment by Software-Noob** [comment]
Implemented rusk wipe scheduled task instead, as I do not see any other good reason for a scheduled reinstall, since it could easily lock a server if wrong schedule is setup.
