### ISSUE TITLE
Select items not full width of select container

### ISSUE THREAD

**Issue by DarthShmev** [wisp-gg/frontend#25]
**Describe the bug**
When opening a select, the items (options) do not take up the full width of the select container, leaving some black space on the right side.

**To Reproduce**
Open any dropdown, for instance, on the user account settings language setting.

**Expected behaviour**
I would expect the options to fill the width of the container.

**Screenshots**
<img width="259" alt="Screen Shot 2022-02-13 at 10 35 55 AM" src="https://user-images.githubusercontent.com/34663790/153760726-027194c2-6312-472f-90a3-eaa16650d393.png">

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser: Safari & Chrome

Thanks again for all your work! :)

**Comment by WISPdotGG** [comment]
I think that's space for the scrollbar when there are more options

**Comment by victiondev** [comment]
thats the browser scrollbar as driz mentioned. wontfix because its a very minor thing and not really causing any issues.
