### ISSUE TITLE
All emails default to french

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/frontend#250]
### Describe the bug

When receiving an email the default language is French

### Expected Behavior

I expect the language to default to English if no other language is set for the user or being able to set a default language

### Actual Behavior

When receiving an email the default language is French

### Steps to Reproduce

Make a new user or subuser
Check inbox
See issue

### Browser Details

Chrome 100

### Operating System

Windows 10

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.
