### ISSUE TITLE
Minecraft Different Edition Installer Latest/Recommended Visual Bug

### ISSUE THREAD

**Issue by ThePlay3r** [wisp-gg/frontend#251]
### Describe the bug

Different Edition installer for Minecraft shows `Latest` and `Recommended` for the same Minecraft version (eg. `1.16.5`) as a single version, when in fact it should be separate.

![image](https://user-images.githubusercontent.com/29305429/162579743-ee08194e-3dd9-461c-9b59-49909aedd568.png)

![image](https://user-images.githubusercontent.com/29305429/162579769-4ba74e27-6e9e-441d-9702-1bae78127df2.png)

### Expected Behavior

I expect it to show `Latest` and `Recommended` as 2 separate versions.

### Actual Behavior

It shows `Latest` and `Recommended` as a single version, clicking on it sets it to the recommended one.

### Steps to Reproduce

Step 1 - Create Minecraft server
Step 2 - `Configuration` > `Advanced`
Step 3 - Try to change the version to **latest** `Forge 1.16.5`

### Browser Details

Firefox Developer Edition 100.0b3 (64-bit)

### Operating System

Windows 11

**Comment by TrixterTheTux** [comment]
Should be fixed.
