### ISSUE TITLE
Schedule gets wrong calculations on hours

### ISSUE THREAD

**Issue by vanjmali** [wisp-gg/frontend#252]
### Describe the bug

When doing `every # hours` statements for a schedule, it gets next runs time wrongly.

### Expected Behavior

Correctly display the time.

### Actual Behavior

Displays the time with odd calculations and different outputs at different locations

(Time of recording displayed on Windows taskbar was 9:24PM, 9th April 2022)

https://user-images.githubusercontent.com/31445914/162588927-944373ae-d6b6-4b4d-a535-ab32db325651.mp4

### Steps to Reproduce

Step 1 - Go to Schedule Manager
Step 2 - Create a new schedule
Step 3 - Set the minute time to `0`
Step 4 - Set the hour time to every `3` hours
Step 4 - Save the changes and see "Next run" time

### Browser Details

Microsoft Edge Version 100.0.1185.36 (Official build) (64-bit)

### Operating System

Windows 11 Pro

### Optional additional information

```bash
It was not tested if the schedule would trigger at the correct time or the one displayed next run approximation.
```

**Comment by 0xCiBeR** [comment]
I think this is DUP for #233

**Comment by vanjmali** [comment]
Ah, looks like that is the case. I'll close this one then.
Thanks for mentioning it, I wasn't actually able to find it 😅
