### ISSUE TITLE
COMPLETE BRANDING REMOVAL

### ISSUE THREAD

**Issue by zapz12** [wisp-gg/frontend#258]
### Describe the feature and why you would like to see it.

Currently the console shows  [WISP] 
![image](https://user-images.githubusercontent.com/56172312/163437033-8e3a00ec-9ace-436a-915b-bdaa22333d6c.png)

### Describe the solution you'd like.

Have the ability to change that for enterprise customers

**Comment by victiondev** [comment]
This is customisable in the daemon config already. https://www.notion.so/Daemon-Customisation-1073b5d307bb41709b56a2e11b8437c5#72cd8b4b51d74846a282eaafc01d6193
