### ISSUE TITLE
LIMITS WHEN INSTALLING DEPENDENCIES

### ISSUE THREAD

**Issue by zapz12** [wisp-gg/frontend#259]
### Describe the feature and why you would like to see it.

Currently the process is killed if a dependency installation takes too many resources (node dependencies) 

### Describe the solution you'd like.

Ability to enable more resources for dependencies installation

**Comment by TrixterTheTux** [comment]
Per-process memory limits aren't something that'll really be implemented due to the technical complexity - you should allocate enough memory for the server that it can perform those actions instead.
