### ISSUE TITLE
Schedule Stuck in Processing when not manually or on time

### ISSUE THREAD

**Issue by Abys5** [wisp-gg/frontend#26]
**Describe the bug**
When on the Schedule page it has processing, even though i have not pressed Run or the time hasn't been met.

**To Reproduce**
Unknown

**Expected behavior**
Shouldn't be processing

**Screenshots**
[Image](https://i.imgur.com/a3ezQkt.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Brave

**Comment by WISPdotGG** [comment]
https://dino.gg/server/27496514/schedules

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.
