### ISSUE TITLE
Migrating dbs when using move server function doesnt work

### ISSUE THREAD

**Issue by 0xCiBeR** [wisp-gg/frontend#263]
### Describe the bug

When moving a server to another node, migrator tries to move dbs also but always seems to fail, no matter the size of the DB.
<img width="288" alt="image" src="https://user-images.githubusercontent.com/9750850/164734601-11e33856-ebaa-4500-8b68-f981bb59547e.png">

### Expected Behavior

DBs should be migrated to equivilant db host of the new node and not fail.

### Actual Behavior

Fails db migration always

### Steps to Reproduce

1.) Move a server that has a db associated to another node
2.) Watch how db migration fails

### Browser Details

Chrome Version 98.0.4758.109

### Operating System

MacOS Monterey 12.2.1

**Comment by TrixterTheTux** [comment]
I don't see any relevant logs on our end that would indicate an issue on our end - you'd need to open a support ticket with relevant information (both db host's IP, which node was shown in the footer of the page when starting the transfer, database size) for us to be able to look into this.
