### ISSUE TITLE
Subdomains Created Not Listed in Admin Area

### ISSUE THREAD

**Issue by falceso** [wisp-gg/frontend#264]
### Describe the bug

With the new release of the subdomain manager, trying to view all the created subdomains for a domain is broken.

### Expected Behavior

When visiting the "Servers" page in the Domain Manager, you should see all subdomains that have been created.

### Actual Behavior

"No items" are listed, despite having 23 subdomains that have claimed to be created on the Domain Homepage.

### Steps to Reproduce

Step 1 _(Assuming you already have a subdomain created through the Subdomain Manager)_ - Visit the Admin Area and click on Domains.
Step 2 - Select the Domain Name that has servers associated with it.
Step 3 - Visit the "Servers" page to presumably view what subdomains were created.
Step 4 - Notice how there's nothing listed.

### Browser Details

Chrome 100

### Operating System

Windows 10

**Comment by victiondev** [comment]
Fixed in next release - though I plan to rework that page regardless
