### ISSUE TITLE
Support OPS do not have permission to access the Backups section

### ISSUE THREAD

**Issue by grimesy88** [wisp-gg/frontend#268]
### Describe the bug

My support OPS do not have access to "Backups" its greyed out in the nav menu.

### Expected Behavior

Support OPS to be able to access backups

### Actual Behavior

Support OPS see that the Backups option is greyed out

### Steps to Reproduce

Get a support OP to attempt to access Backups and see that it is greyed out.

### Browser Details

Chrome

### Operating System

Windows 11

### Optional additional information

```bash
asdas
```

**Comment by victiondev** [comment]
fixed in next release
