### ISSUE TITLE
Blocked by CORS policy - WidgetBot

### ISSUE THREAD

**Issue by vanjmali** [wisp-gg/frontend#27]
**Describe the bug**
Importing the WidgetBot now gets a full list of errors in the console. More notable: `blocked by CORS policy` issue. The
```
Access to XMLHttpRequest at 'https://cdn.wisp.gg/uploaded_assets/example.com/11e11d7da9b9d6f34d6374188e4a1bf22b004c3911f3b71064176d77123e463e.js'from origin 'https://example.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**To Reproduce**
1. Import WidgetBot to JSInject
2. Refresh the page after saving
3. Check console

**Expected behavior**
WidgetBot displaying the Discord icon without those errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/31445914/153760827-6496ae2f-e3c4-467b-b810-e32687e46297.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge
 - Version 98.0.1108.50

**Comment by TrixterTheTux** [comment]
Could you check if it works now? Chances are it was being affected by https://github.com/wisp-gg/frontend/commit/820237a78d7d6259a9c6288f023d3d317ed30900.

**Comment by vanjmali** [comment]
The issue has been solved, thank you. I appreciate it!
