### ISSUE TITLE
Mod installer issue.

### ISSUE THREAD

**Issue by ProfessionalWumpus** [wisp-gg/frontend#275]
### Describe the bug

When I try to uninstall a mod it throws an error and after server reinstallation the mod tab tills show an Uninstall button.

https://media.discordapp.net/attachments/749570444734103584/970890177922863144/unknown.png?width=882&height=1367

### Expected Behavior

It should uninstall the mod without a red error box. :)

### Actual Behavior

Just throws an error with no mods deleted :(

### Steps to Reproduce

1. Uninstall a mod.

### Browser Details

Microsoft Edge, Chrome, Safari

### Operating System

MacOS 12.2.1

**Comment by TrixterTheTux** [comment]
Spamming the action will cause you to get rate-limited and thus cause the request to timeout.
