### ISSUE TITLE
Mod Manager Install/uninstall status

### ISSUE THREAD

**Issue by Matt-nwt** [wisp-gg/frontend#276]
### Describe the bug

When installing or uninstalling a mod using the mod manager, the status does not change automatically (without manually refreshing the page).

### Expected Behavior

After install, installed mod should say uninstall (this indicates to the user that the mod has in fact installed)
After uninstall, mod should say install (this indicates to the user that the mod has in fact uninstalled)

### Actual Behavior

After install, installed mod still displays "Install" (this indicated to the user that the install has failed)
After uninstall, mod still displays "uninstall" (this indicated to the user that the uninstall has failed)

### Steps to Reproduce

Step 1 - click install on mod
Step 2 - wait for install to run
Step 3 - observe that "install" is still showing
Step 4 - manually refresh page to show correct status
Step 5 - click uninstall
Step 6 - wait for uninstall to run
Step 7 - observe that "Uninstall" is still showing. 

### Browser Details

Chrome 100.0.4896.127

### Operating System

Windows 10

**Comment by victiondev** [comment]
fixed in next release
