### ISSUE TITLE
Console resize issue

### ISSUE THREAD

**Issue by WISPdotGG** [wisp-gg/frontend#279]
### Describe the bug

Console doesn't resize correctly when window is resized

### Expected Behavior

Console to stay the same relative size in the window

### Actual Behavior

The horizontal scrollbar appears and the console sometimes gets too big for the window even when fullscreen, essentially softlocking the page and needing the user to refresh

### Steps to Reproduce

Resize window on console page

### Browser Details

Chrome 102.0.5005.22

### Operating System

Chrome 102.0.5005.22

### Optional additional information

```bash
https://cdn.discordapp.com/attachments/449546780691136534/972591494978502726/Screen_recording_2022-05-07_9.10.03_PM.webm
```

**Comment by TrixterTheTux** [comment]
This should've been fixed a while ago - if this isn't the case, let me know and I'll reopen this.
