### ISSUE TITLE
Discord Link

### ISSUE THREAD

**Issue by roguebros23** [wisp-gg/frontend#280]
### Describe the feature and why you would like to see it.

The **Discord Link Feature** would have a Link where Clients can click on to join the Discord Server. I think other Hosting providers would like this feature.

### Describe the solution you'd like.

The solution would be a link that is provider by the Server Owner.

**Comment by victiondev** [comment]
I don't see much use for this currently and it's never been requested before this - adding custom links will also be possible with theming when it releases. In the future we may add a generic way to add external links.
