### ISSUE TITLE
Inaccurate description for DB host FQDN field

### ISSUE THREAD

**Issue by TrixterTheTux** [wisp-gg/frontend#281]
### Describe the bug

Currently, the DB host FQDN field has the following footer: "The IP address or FQDN that should be used when attempting to connect to this MySQL host from the panel to add new databases."

This isn't actually accurate after refactor due to the DNS lookup logic being removed (thus it only accepts IP).

### Expected Behavior

Either we'd need to implement that logic back or consider allowing DB hosts to use FQDNs directly? Though that's probably too much work for any notable gain as one-time changing DB host IPs should be a non-issue.

### Actual Behavior

Any non-IP FQDN is rejected.

### Steps to Reproduce

* Create a Database Host
* Enter into FQDN "example.com" as value

### Browser Details

Firefox 99.0.1

### Operating System

MacOS

**Comment by drizmans** [comment]
Resolved 03992617d5ee9100200fbdd6e6b3edfcc5a301e0
