### ISSUE TITLE
Notification of modpack installing when a user clicks install

### ISSUE THREAD

**Issue by Shybella** [wisp-gg/frontend#283]
### Describe the feature and why you would like to see it.

When a user goes to click the install button for a minecraft modpack, it needs a window popup letting them know the pack is being installed. I have people that keep clicking the install button thinking its doing nothing.

### Describe the solution you'd like.

Some of kind button/modpack install lock while the pack is installing and notifications of installing and upon completetion

**Comment by TrixterTheTux** [comment]
Should be implemented in the next release.
