### ISSUE TITLE
Ability to retrieve external users.

### ISSUE THREAD

**Issue by ThePlay3r** [wisp-gg/frontend#284]
### Describe the feature and why you would like to see it.

I would like to have the ability to retrieve external users using the new Admin API, like it was possible with legacy Application API. (`api/application/users/external/<id>`)

### Describe the solution you'd like.

As mentioned above, simple `/api/admin/users/external/<id>` endpoint, or something similar would do the trick.

**Comment by victiondev** [comment]
done in next release (/api/admin/users/external/:id)
