### ISSUE TITLE
Notify user that a archive is being decompressed

### ISSUE THREAD

**Issue by DelxHQ** [wisp-gg/frontend#285]
### Describe the feature and why you would like to see it.

As of the WISP latest version, when you press decompress on an archive, nothing happens UI side thus causing a confusion making the user think their archive isn't being decompressed. There should be some sort of progress bar letting the user know that the archive is being decompressed.

### Describe the solution you'd like.

Notify the user that an archive is being decompressed with a progress bar

**Comment by Larsdeijsbeer** [comment]
It looks like this still hasn't been implemented.
