### ISSUE TITLE
[UX] Missing field descriptions in allocations tab

### ISSUE THREAD

**Issue by Software-Noob** [wisp-gg/frontend#288]
### Describe the bug

The allocations page does not contain any description for the input fields, unlike in WISP v1. This can be quite a confusing experience for a new user and chances are, they will fill the alias field with something as well.

### Expected Behavior

Describe the input field to the end-user and optionally link to documentation as many users have no clue on what IP they're supposed to use.

### Actual Behavior

Input fields with no descriptions

![image](https://user-images.githubusercontent.com/10975908/169049587-46f530d7-5554-4631-b418-bd8285a7d1d1.png)

### Steps to Reproduce

Step 1 - Navigate to the Node Allocations tab
Step 2 - View create a new  allocation modal
Step 3 - As a potential new user, be very confused.

### Browser Details

FireFox 100

### Operating System

Linux

**Comment by victiondev** [comment]
fixed in next release
