### ISSUE TITLE
Schedules-Error

### ISSUE THREAD

**Issue by CookieMC337** [wisp-gg/frontend#29]
**To Reproduce**
1. Go to 'Server-Manage'
2. Click on 'Schedules'
3. Create new
3. Edit any Value

**Screenshots (no gif)**
https://i.imgur.com/fB4QBQh.gif

**Desktop:**
 - OS: Windows 11
 - Browser chrome
 - Version idk

**Comment by WISPdotGG** [comment]
This is fixed
