### ISSUE TITLE
New Server - Secondary allocations not functioning

### ISSUE THREAD

**Issue by Matt-nwt** [wisp-gg/frontend#291]
### Describe the bug

when creating a new server, specifying additional ports in the  "SECONDARY ALLOCATIONS" does not work. The server is created without the allocations which then have to be added manually.

### Expected Behavior

secondary allocations should be assigned when the server is created.

### Actual Behavior

secondary allocations are not created / assigned.

### Steps to Reproduce

Step 1 - on the Create a server page, setup a server  (can be any egg) and specify "SECONDARY ALLOCATIONS"
Step 2 - Create Server
Step 3 - observe no secondary allocations have been assigned.

### Browser Details

Chrome 100.0.4896.127

### Operating System

Windows 10

**Comment by Software-Noob** [comment]
I can't reproduce this - please reopen the issue if you are still encountering this.
