### ISSUE TITLE
Add QuiltMC to versoin installer list

### ISSUE THREAD

**Issue by vanjmali** [wisp-gg/frontend#299]
### Describe the feature and why you would like to see it.

[QuiltMC](https://quiltmc.org/) mod loader is a fork of Fabric. They support loading Fabric mods and will be like that for some time while it can, lots of mods are starting to move to it due to better API and the active team moving there so there might be more usage of Quilt.

### Describe the solution you'd like.

Quilt installer would work very similarly to Fabric's installer, possibly even the same.

**Comment by TrixterTheTux** [comment]
Should be implemented.
