### ISSUE TITLE
Server-list pages not working

### ISSUE THREAD

**Issue by ThePlay3r** [wisp-gg/frontend#3]
**Describe the bug**
As title says, when trying to switch to another serverlist page, it doesn't work.

**To Reproduce**
1. Go to 'Main Page/Server List'
2. Click on 'For example seconds page/page change button.'
3. Nothing happens. (Site refreshes, same page)

**Expected behavior**
I expect to see other/next page of servers.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 98.0b3

**Comment by WISPdotGG** [comment]
Mistake, not a duplicate of this issue

**Comment by TrixterTheTux** [comment]
Should be fixed in next release.
