### ISSUE TITLE
Modpack Manager - Admin Install | No Notification

### ISSUE THREAD

**Issue by falceso** [wisp-gg/frontend#303]
### Describe the bug

When a Panel Administrator installs a modpack for a Client, they do not receive an notification that the modpack was successfully installed. Only if they are a the server owner or a sub-user will they receive the panel notification of completion.

### Expected Behavior

If an administrator installs a modpack on behalf of a client, they should also receive a notification whether the modpack was successfully installed or not.

### Actual Behavior

Only the server owner and sub-users are notified of a modpack install.

### Steps to Reproduce

Step 1 - Test with a server that you are not the server owner or a sub-user.
Step 2 - Install a new modpack as a Panel Admin not associated to the server.
Step 3 - Notice how the Server Owner and Sub-User are notified but not you, the Panel Admin who installed it.

Step 4 _(Optional)_ - Test with a server you're a sub-user or server owner.

### Browser Details

Chrome 102

### Operating System

Windows 10

**Comment by victiondev** [comment]
added in next rleease
