### ISSUE TITLE
Error when deleting security keys

### ISSUE THREAD

**Issue by 0xCiBeR** [wisp-gg/frontend#304]
### Describe the bug

When trying to delete a security key, it doesn't delete it and shows an error in console:
![image](https://user-images.githubusercontent.com/9750850/174345383-c2230e2c-d3d1-45b1-a0ed-e87e151e24e0.png)

### Expected Behavior

Deletion of security key

### Actual Behavior

Key does not get deleted and shows error in console. No output in UI

### Steps to Reproduce

1) Name a security key samsung s21 ultra
2) Try to delete it

### Browser Details

Chrome

### Operating System

Windows 11

**Comment by victiondev** [comment]
fixed in next release
