### ISSUE TITLE
fivem server cache folder 

### ISSUE THREAD

**Issue by Yavzkesta** [wisp-gg/frontend#306]
### Describe the bug

in fivem server the cache folder is not counted in the disk usage monitor

### Expected Behavior

is posibel to add this iformation ?

### Actual Behavior

.

### Steps to Reproduce

after start fivem server cache folder is auto created and space used is not integrate in monitor

### Browser Details

firefox

### Operating System

windows

**Comment by Yavzkesta** [comment]
for exempel after fivem server started he create cache folder in root folder
![image](https://user-images.githubusercontent.com/48090660/175127983-3024b555-de8e-4ad6-acef-d72145d8f878.png)
and used space information is not counted in 
![image](https://user-images.githubusercontent.com/48090660/175128103-192ca612-c3eb-4774-b75f-464d911a726c.png)

**Comment by victiondev** [comment]
What makes you think its not counted? We don't exclude any folders from the disk usage check - we simply run `du -hsb {server_file_directory} and return the value.

**Comment by Yavzkesta** [comment]
I don't think so, I just know
you should know that fivem generates a cache that is about the size of the resource folder,
we suffer a blocking of file sending but we don't have the information of the use!

**Comment by Yavzkesta** [comment]
before achived folder
![2022-06-24 09_47_57-_Sans titre - Bloc-notes](https://user-images.githubusercontent.com/48090660/175489942-c3fc5217-7110-4a5e-b679-a92f857c94c0.png)

after archive look space used !
![image](https://user-images.githubusercontent.com/48090660/175489905-0e3a8064-afe8-4112-98c0-8cf21ac4f611.png)

**Comment by drizmans** [comment]
The issue was the sftp-server counting hard linked files as copies instead of just once. This is fixed in the beta branch & rolling out to production on Monday
