### ISSUE TITLE
Panel Timeout Compressing A Folder

### ISSUE THREAD

**Issue by falceso** [wisp-gg/frontend#308]
### Describe the bug

When compressing a big directory, the panel quickly times out while the process is still running in the background. This causes confusion for the client and they run the archive request more than once.

### Expected Behavior

The file management simply refreshes and possibility tells the user the filename of the archive, so they know which file to look for.

### Actual Behavior

You get the error "There was an exception while attempting to communicate with the daemon."

![https://i.imgur.com/InXHr6V.png](https://i.imgur.com/InXHr6V.png)

### Steps to Reproduce

Step 1 - Have a big directory you want to compress.
Step 2 - Compress the directory.
Step 3 - Check for the error message.

![https://i.imgur.com/eEpk78Y.gif](https://i.imgur.com/eEpk78Y.gif)

### Browser Details

Chrome 103

### Operating System

Windows 10

**Comment by Larsdeijsbeer** [comment]
I'm still having this issue. 
It's really unclear to the user that the file has been created. I've seen users creating a lot of compressed files and filling their disk completely because of the timeouts.

**Comment by victiondev** [comment]
increased timeout to 60s in next release so this shouldn't error anymore - when the go daemon rolls around we will probably revisit the UX on this and provide proper progress reports somehow.

**Comment by falceso** [comment]
Bumping this issue as a few clients are experiencing this still, not sure what the size of there server are but they are definitely opening tickets and generating more archives not knowing its working in the background.
