### ISSUE TITLE
Navigation logo goes to "https://cdn.wisp.gg/" when opening in a new tab.

### ISSUE THREAD

**Issue by CooperWinser** [wisp-gg/frontend#31]
**Describe the bug**
When clicking the logo in the top left, it works as normal. However, using right click and opening it in a new tab goes to "https://cdn.wisp.gg/".

**To Reproduce**
1. Right click the logo in the top left, and select "Open Link in New Tab".
2. It takes you to "https://cdn.wisp.gg/" instead of the panels URL.

**Expected behavior**
It should take you to the panel homepage, i.e. panel.domain.com.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 97.0

**Comment by DarthShmev** [comment]
Low priority I'd say, left clicking on the logo works fine.

**Comment by WISPdotGG** [comment]
This also happens with the server cards on the homepage too, bumping to high priority

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.
