### ISSUE TITLE
Maintenance Mode Option Not Saved - Node Settings

### ISSUE THREAD

**Issue by falceso** [wisp-gg/frontend#317]
### Describe the bug

When toggling the "Maintenance Mode" option to prevent users from accessing servers. This toggle is not saved when refreshed.

### Expected Behavior

The maintenance mode toggle works and users will be unable to access their servers.

### Actual Behavior

The toggle is turned back off/doesn't save its state of being enabled.

### Steps to Reproduce

Step 1 - Visit the Node Settings for a Node.
Step 2 - Toggle the Maintenance Mode option to be enabled.
Step 3 - Save the setting changes with the button on the bottom right.
Step 4 - Refresh the page and realize the change was not registered.

### Browser Details

Chrome 103

### Operating System

Windows 10

**Comment by Software-Noob** [comment]
Fixed in the next release
