### ISSUE TITLE
"Disable OOM Killer" setting not saving from initial server setup

### ISSUE THREAD

**Issue by brandonsturgeon** [wisp-gg/frontend#329]
### Describe the bug

When creating a server, if you toggle-on the "Disable OOM Killer" option, it will still be un-toggled in the "Build Configuration" page after creating the server.

### Expected Behavior

The "Disable OOM Killer" option should status selected in the initial server setup

### Actual Behavior

The "Disable OOM Killer" option will always be "off" after creating the server, no matter what option was selected during setup.

### Steps to Reproduce

 - Begin creating a new server
 - Fill out all required fields
 - Toggle "Disable OOM Killer" on
 - Create the server
 - Visit the "Build Configuration" page of the created server
 - Observe "Disable OOM Killer" being un-toggled

### Browser Details

104.0.1 (64-bit)

### Operating System

Windows 10

### Optional additional information

**During setup:**
![firefox_bKqUfWob8G](https://user-images.githubusercontent.com/7936439/189221509-6844aae0-cca9-4b5b-aaad-21ac9fc22f00.png)

**In Build Configuration:**
![firefox_0OSiuXud3Q](https://user-images.githubusercontent.com/7936439/189221523-a10dc495-98a0-42aa-b159-7a0b7e283cd5.png)

**Comment by drizmans** [comment]
this is fixed, to be rolled out soon - from SoftwareNoob on the cause:
oom was never validated so any API calls wouldn't catch it
