### ISSUE TITLE
Some servers not showing CPU usage when online

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/frontend#33]
**Describe the bug**
Some servers not showing CPU usage when online

**To Reproduce**
1. Go to Main Page
2. See error

**Expected behavior**
I expect the CPU usage to be shown for all servers

**Screenshots**
![picture](https://user-images.githubusercontent.com/61161558/153761025-fef84ebf-e1ad-4644-aec0-5ebc7ddf125a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 98.0.4758.82

**Comment by WISPdotGG** [comment]
Possibly related to #18

**Comment by victiondev** [comment]
fixed in latest release
