### ISSUE TITLE
Pixelmon Latest Version not being installed 

### ISSUE THREAD

**Issue by ElectrumIsPog** [wisp-gg/frontend#334]
### Describe the bug

> You cannot install the latest versions of Pixelmon [9.0.9+](https://www.curseforge.com/minecraft/mc-mods/pixelmon/files/3990855)

### Expected Behavior

You should be able to see and install the latest version 

### Actual Behavior

Only up to version 9.08 is shown

### Steps to Reproduce

1: Tools > Modpack manager
2: Attempt to install latest Pixelmon, you will only be shown up to version 9.08

### Browser Details

Firefox 104.0

### Operating System

Windows 11

**Comment by TrixterTheTux** [comment]
This should be now fixed.
