### ISSUE TITLE
Can't find the last update | Modpack

### ISSUE THREAD

**Issue by SNokerYT** [wisp-gg/frontend#335]
### Describe the bug

Can't find the last update

### Expected Behavior

.

### Actual Behavior

.

### Steps to Reproduce

1: Tools > Modpack manager
2: Attempt to install the latest MC ETERNAL, you will only be shown up to version 1.4.3.1

### Browser Details

Google chrome 

### Operating System

Windows

**Comment by TrixterTheTux** [comment]
This should be fixed.
