### ISSUE TITLE
High CPU usage on FastDL compression in WISP

### ISSUE THREAD

**Issue by pedrotski** [wisp-gg/frontend#339]
### Describe the bug

There is extremely high CPU usage during the compression of FastDL files. It looks like its also caused by multiple files being compressed at once. Here is a screenshot of a 5900x with nvme in raid 0 with 2 fastdl syncs going at once. 

https://imgur.com/a/yuQ7uex

This is not going to be an issue with small fastdl sizes, but when you have lots of maps a sync can take 5 - 10 mins.

### Expected Behavior

Only the files that have been modified/added should be updated to save resources on subsequent syncs. It might also be worth while only compressing one file at a time. I cant confirm if it was compressing multiple files at once, only what htop displayed.

Here is a script that works in that way - https://github.com/GAMMACASE/FastdlUpdater

### Actual Behavior

All files are recompressed regardless of modified state. 

### Steps to Reproduce

Step 1. Upload lots of maps
Step 2. Sync the fastdl

### Browser Details

Chrome

### Operating System

Ubuntu 20.04

**Comment by pedrotski** [comment]
It seems as though large map directories also don't fully compress. I have 2 totally different dedis here and both are not compressing all the files in the maps directly. 

Server A: 841 files out of 1083
Server B: 984 files out of 4694

Nothing is in the logs about this failing either. One server is 70gb of maps, the other is around 100gb

The attached file showed where it gets cut off. The maps end up all the way to ze_z and bhop_z but it failed before it gets there. 
![Uboth_endingitled](https://user-images.githubusercontent.com/58076186/195092438-8714d4a0-c7c4-4e8c-bf78-95c6f37c05a3.jpg)

**Comment by pedrotski** [comment]
Looking into this again as we kinda need a quick resolution.

It seems the fastdl sync is only syncing to the files listed on page 10 of the WISP panel itself. 

It may simply be a matter of increasing the amount of files listed so we could actually use this feature. 

![fghfghfged](https://user-images.githubusercontent.com/58076186/201529011-67c5dc61-a19d-4415-8629-d4d07e95f4c2.jpg)

**Comment by TrixterTheTux** [comment]
The top 1000 files only being compressed for FastDL should be fixed in the next release, and it'll also introduce the `fastdl.concurrent_files` config option (needs to be added by hand) that allows you to control how many files should be concurrently compressed/moved, with the default set to 5 files.

Regarding not compressing already compressed files, that's probably a goal for the golang daemon currently being worked for as it would require either way reworking the FastDL system.

**Comment by pedrotski** [comment]
Thanks for the response. When is the next release planned? Right now for our level of servers this function is not usable.

**Comment by TrixterTheTux** [comment]
Most likely tomorrow or at least by the end of this week.

**Comment by pedrotski** [comment]
Just an update. Fastdl compresses all the files as intended now. Thanks for that!

If I have a suggestion for the rewrite would be to allow people to put in external FTP or sftp details too.

**Comment by Software-Noob** [comment]
implemented in the next release

**Comment by pedrotski** [comment]
> It seems as though large map directories also don't fully compress. I have 2 totally different dedis here and both are not compressing all the files in the maps directly.
> 
> Server A: 841 files out of 1083 Server B: 984 files out of 4694
> 
> Nothing is in the logs about this failing either. One server is 70gb of maps, the other is around 100gb
> 
> The attached file showed where it gets cut off. The maps end up all the way to ze_z and bhop_z but it failed before it gets there. ![Uboth_endingitled](https://user-images.githubusercontent.com/58076186/195092438-8714d4a0-c7c4-4e8c-bf78-95c6f37c05a3.jpg)

This bug has returned after the most recent update.

**Comment by SaltysKing** [comment]
> > It seems as though large map directories also don't fully compress. I have 2 totally different dedis here and both are not compressing all the files in the maps directly.
> > Server A: 841 files out of 1083 Server B: 984 files out of 4694
> > Nothing is in the logs about this failing either. One server is 70gb of maps, the other is around 100gb
> > The attached file showed where it gets cut off. The maps end up all the way to ze_z and bhop_z but it failed before it gets there. ![Uboth_endingitled](https://user-images.githubusercontent.com/58076186/195092438-8714d4a0-c7c4-4e8c-bf78-95c6f37c05a3.jpg)
> 
> This bug has returned after the most recent update.

Bumping as having same issue.
