### ISSUE TITLE
Update server button vanished

### ISSUE THREAD

**Issue by Larsdeijsbeer** [wisp-gg/frontend#34]
**Describe the bug**
I can't find the Update Server button which runs the update script. 

**To Reproduce**
1. Go to 'a random server'
2. Click on 'configuration > advanced'

**Expected behavior**
Update server button to run the script

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Chrome
 - Version 98

**Comment by TrixterTheTux** [comment]
This seems to work for me on the production instance. Is the nest not set to `srcds` by any chance?

**Comment by Larsdeijsbeer** [comment]
I'm using the update button to update a Geysermc server. So no, it isn't set to `srcds`.

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.
