### ISSUE TITLE
Can't find TNP Limitless 6

### ISSUE THREAD

**Issue by SNokerYT** [wisp-gg/frontend#341]
### Describe the bug

Can't find TNP Limitless 6
https://www.curseforge.com/minecraft/modpacks/tnp-limitless-6

### Expected Behavior

...

### Actual Behavior

...

### Steps to Reproduce

...

### Browser Details

...

### Operating System

...

### Optional additional information

```bash
...
```

**Comment by drizmans** [comment]
This has since been added, closing
