### ISSUE TITLE
DNS config in wisp.yaml is not used in install containers

### ISSUE THREAD

**Issue by 0xCiBeR** [wisp-gg/frontend#345]
### Describe the bug

When installing a server, the container that is created to install the server files does not use the config setup in **/var/lib/wisp/daemon/config/wisp.yaml**

You can check this setting appropiate config and then running an install. Do a **docker inspect** and see that DNS field is null.

### Expected Behavior

All containers ran by wisp should use DNS settings set in config.

### Actual Behavior

Wisp ignores dns config for install containers.

### Steps to Reproduce

1-) Specify dns servers in wisp config
2-) Restart wisp and the trigger a server install
3-) Do a **docker ps** to get install container ID then **docker inspect ID**
4-) View how that container doesn't have any overrides for dns, and instead you see "DNS": null

### Browser Details

Doesnt apply

### Operating System

Doesnt apply

**Comment by victiondev** [comment]
fixed in next release
