### ISSUE TITLE
can't find Vault Hunters 3rd Edition (MODPACK)

### ISSUE THREAD

**Issue by SNokerYT** [wisp-gg/frontend#355]
### Describe the bug

Can't find Vault Hunters 3rd Edition
https://www.curseforge.com/minecraft/modpacks/vault-hunters-1-18-2

### Expected Behavior

.

### Actual Behavior

.

### Steps to Reproduce

.

### Browser Details

Google chrome

### Operating System

Windows

**Comment by drizmans** [comment]
This has since been added, closing
