### ISSUE TITLE
Backup schedule can crash an entire node

### ISSUE THREAD

**Issue by Larsdeijsbeer** [wisp-gg/frontend#356]
### Describe the bug

The scheduler is able to start the creation of a backup while another backup is still running. This creates a loop of backups which can cause an entire node to crash.
I've experienced this multiple times. 

### Expected Behavior

Don't start multiple backup processes.
It shouldn't ignore the user limits (like disk size limit)

### Actual Behavior

It completely fills the disk (even when the user has a 20GB backup limit). So it ignores the user limits. Because it starts creating a lot of backups this also causes full cpu utilization on the node. Even when the user has a limit of 200%. 

Disk usage (node)
![image](https://user-images.githubusercontent.com/27996312/209434160-fd88f6a4-7eca-4e8c-a1e8-ebfc720b6132.png)

A lot of backups are running at the same time
![image](https://user-images.githubusercontent.com/27996312/209434169-cddcf2cb-e49c-4d92-bd07-cfa97659e847.png)

### Steps to Reproduce

Create a schedule like this:
![image](https://user-images.githubusercontent.com/27996312/209434286-a1a82ac0-2d35-4f71-a921-c76c2448a7cd.png)

It should create a backup every minute.

### Browser Details

Chrome

### Operating System

Windows 10

### Optional additional information

Have fun crashing hosts using Wisp!

**Comment by TrixterTheTux** [comment]
Backup creation should be throttled in the next release to 2 backups/10 minutes
