### ISSUE TITLE
Location not working for "move server to another node"

### ISSUE THREAD

**Issue by Larsdeijsbeer** [wisp-gg/frontend#357]
### Describe the bug

The "move server to another node" feature ignores the location dropdown.

### Expected Behavior

It should filter the listed nodes by the chosen location.

### Actual Behavior

It shows all of the locations and nodes. It doesn't filter anyting.

### Steps to Reproduce

Use the server move feature.
![image](https://user-images.githubusercontent.com/27996312/209434831-0d84100a-e237-4b43-9580-aedc7ea0eb44.png)

### Browser Details

Chrome

### Operating System

Windows 10

**Comment by Software-Noob** [comment]
This has since been fixed, please reopen if you are still able to reproduce
