### ISSUE TITLE
Console enhancement 

### ISSUE THREAD

**Issue by Larsdeijsbeer** [wisp-gg/frontend#363]
### Describe the feature and why you would like to see it.

I really would like to see a / inside the command field of the console.
![image](https://user-images.githubusercontent.com/27996312/209435312-d88a3cde-1d34-46bf-b473-bb4e05769364.png)

### Describe the solution you'd like.

Because it's showing a $ instead of a / clients think they need to add a / to run a command (Minecraft).
It returns "unknown command" because of this. This is unclear to the client.

**Comment by drizmans** [comment]
Solved by 8d5e803647f2cd2dce212ee1fccab29ae51e9380
