### ISSUE TITLE
Use a centralized database host

### ISSUE THREAD

**Issue by Larsdeijsbeer** [wisp-gg/frontend#364]
### Describe the feature and why you would like to see it.

I would like to use one host for all of the databases. Now I have to create a database host for every node.

### Describe the solution you'd like.

Allow a database host to be chosen for multiple nodes. This way I can create one database host and use it for every node.

Here you should be able to select multiple nodes (or just all nodes)
![image](https://user-images.githubusercontent.com/27996312/209435459-9d060aeb-153d-4d94-8478-0b161fa5f335.png)

**Comment by TrixterTheTux** [comment]
In admin area, in the settings tab there's the option "Enable database deployment on random nodes" that would allow choosing any host (even if it's not linked to a node) for deploying your databases.

**Comment by Larsdeijsbeer** [comment]
Alright, didn't see that!
