### ISSUE TITLE
Make "No items" clearer

### ISSUE THREAD

**Issue by Larsdeijsbeer** [wisp-gg/frontend#367]
### Describe the bug

![image](https://user-images.githubusercontent.com/27996312/209435976-034410c0-f5a4-4c4f-a549-ee3b200b6b0a.png)
When there's nothing to display it shows "No items". 
The Create button is almost hidden.

### Expected Behavior

Show something like:
"No items, click **here** to create a subdomain"

### Actual Behavior

The panel shows "No items" and a very small "Create" button. It should be more clear to the user how to create a subdomain.

### Steps to Reproduce

Use the panel

### Browser Details

Chrome

### Operating System

Windows 10

### Optional additional information

```bash
Same for the backups, databases, sub users, schedules pages.
```

**Comment by drizmans** [comment]
Solved by 29cf1480fa3cb18018a0be2526b552b614b4ee3a
