### ISSUE TITLE
Add save button next to every startup variable

### ISSUE THREAD

**Issue by Larsdeijsbeer** [wisp-gg/frontend#369]
### Describe the feature and why you would like to see it.

It's very unclear to the user how to save a startup variable.
![image](https://user-images.githubusercontent.com/27996312/209436296-cc86ea82-23e2-4ecf-81ff-569ad391111f.png)

### Describe the solution you'd like.

I think it's better to have a "save" button next to every variable. This is much clearer to the user.

**Comment by drizmans** [comment]
There is no save buttons on this page since they save automatically, a save button would have no function and just possibly cause issues as things would save when people didn't click the save button (eg. if you changed your mind after typing something and then find out later it already saved)
