### ISSUE TITLE
Support Ops can’t access Admin Area

### ISSUE THREAD

**Issue by SkyMulley** [wisp-gg/frontend#37]
**Describe the bug**
Panel users with Support Op access can’t access Admin Panel

**To Reproduce**
1. Grant user Support Op
2. Have them go to your-panel.gg/admin
3. Voila

**Expected behavior**
User should be able to access the redacted version of the admin area

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: Latest Stable
 - Browser: FireFox
 - Version: Latest Stable

**Additional context**
Support Op Bypass still does work, all servers are listed. Admin button on the sidebar by the profile still shows up but administrative tab on servers doesn’t

**Comment by JouanDeag** [comment]
Can confirm that Support OPs get a 404 page instead
