### ISSUE TITLE
Out of memory not showing in Audit Logs

### ISSUE THREAD

**Issue by Larsdeijsbeer** [wisp-gg/frontend#372]
### Describe the bug

When a server crashes because it went Out of Memory it doesn't show the reason in the Audit Logs.

### Expected Behavior

Server crashed.
Open the Audit Logs issue and see: "Reason: Out of Memory"

### Actual Behavior

Now it just shows "The server has crashed".
This is very unclear to the user.

### Steps to Reproduce

Let a server crash because of OOM and check the Audit Log entry.

### Browser Details

Chrome

### Operating System

Windows 10

**Comment by falceso** [comment]
Just to make sure we're on the same page, the out of memory status would be appended to the Meta Data displayed under the logUrl, or a new audit item shows up.

**Comment by Larsdeijsbeer** [comment]
Yeah. It would be nice to see it displayed under the LogUrl for example.
Or just remove the LogUrl because it doesn't add any useful information.

**Comment by falceso** [comment]
I would disagree with removing the LogUrl, in some cases it does provide context as to why the server crashed and we do have automatic parsing to determine if a server was killed for out of memory.

**Comment by TrixterTheTux** [comment]
This should be implemented in the next release with also exit code being included. Though as falceso mentioned, the log URL is still useful and won't be removed (what lead to the crash, and it's not guaranteed to be just OOM, etc.).
