### ISSUE TITLE
Audit Logs doesn't always include logs

### ISSUE THREAD

**Issue by Larsdeijsbeer** [wisp-gg/frontend#377]
### Describe the bug

The Audit Logs page doesn't always show an URL containing the server logs from the crash.
I guess this happens because of too much spam in the console? I'm using the Valheim egg.

### Expected Behavior

It should show an URL containing the server logs when the crash happend. 

### Actual Behavior

![image](https://user-images.githubusercontent.com/27996312/209688073-fa4503f4-803a-4cee-8814-ce2d80da2ce9.png)
It only shows "The server has crashed".

### Steps to Reproduce

Let a server crash and check the Audit Logs page.

### Browser Details

Chrome

### Operating System

Windows 10

**Comment by falceso** [comment]
Just to confirm, does the egg include a custom logger?

**Comment by Software-Noob** [comment]
The egg doesn't have log configuration set or something fails during the log upload, in which case daemon logs should contain information about the failure to upload.
