### ISSUE TITLE
SSO text doesn't change with the config.

### ISSUE THREAD

**Issue by Larkify** [wisp-gg/frontend#38]
**Describe the bug**
The "Login with SSO" text on the login page doesn't change to the configured one in the admin settings.

**To Reproduce**
1. Go to admin panel
2. Set the WHMCS module login button text
3. Go the the login page

**Expected behavior**
The text on the button should be what is configured in the admin panel.

**Screenshots**
<img width="333" alt="image" src="https://user-images.githubusercontent.com/69719309/153761620-5c7a17a5-5b0d-4720-b503-563a8130f76d.png">
<img width="283" alt="image" src="https://user-images.githubusercontent.com/69719309/153761643-a09734f0-9e73-4db8-858e-039133a72c75.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser Safari
 - Version 2.0.11

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 15.2.1
 - Browser Safari
 - Version 2.0.11

**Additional context**

**Comment by TrixterTheTux** [comment]
Should have been fixed a while ago but missed this issue.
