### ISSUE TITLE
Turn startup command descriptions into tooltips

### ISSUE THREAD

**Issue by pedrotski** [wisp-gg/frontend#383]
### Describe the feature and why you would like to see it.

I have tried to achieve this with JS but I couldn't get it right. It would help clean things up in startup parameters for clients.  This also includes moving the input rules to the tooltip. 

Right now if descriptions are not the same length the boxes are different height so it looks unfinished. Not to mention for the most part the commands are self-explanatory except for a few. Here is a quick mockup of how it could look like. 

### Describe the solution you'd like.

Here is a quick mockup of how it could look like. 

![mockup](https://i.imgur.com/DGevgCa.png)

**Comment by drizmans** [comment]
Good idea

**Comment by drizmans** [comment]
Done in 48832abb55901f7538ca2ddf20355f075fc0316a
