### ISSUE TITLE
Console command input is not wide enough

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/frontend#385]
### Describe the bug

The input for console commands to servers has a wrong width.
It's either too long or too short depending on the screen size.

### Expected Behavior

I expect it to be lined up.

### Actual Behavior

![image](https://user-images.githubusercontent.com/61161558/228057123-ea59a29d-b27a-4e9e-a054-82424fdc923d.png)
![image](https://user-images.githubusercontent.com/61161558/228057164-8394df04-34ee-4454-933d-52b31166b6b6.png)

### Steps to Reproduce

Go to any server console.

### Browser Details

Chrome 111.0.5563.111

### Operating System

Windows 10

**Comment by drizmans** [comment]
I don't have this issue - what browser are you using?

**Comment by krenny** [comment]
100% zoom Chrome with a 1920x1080 display
![grafik](https://user-images.githubusercontent.com/77990771/228343250-2892c982-07dc-4d89-bf78-46b7b6ab18b9.png)

90% zoom on Firefox with a 2560 x 1440 Display
![grafik](https://user-images.githubusercontent.com/77990771/228343520-9a9e0825-ea06-4d09-a4a4-bf62be489335.png)


Also on Firefox there is a scrolbar(?), not sure if thats releated

**Comment by drizmans** [comment]
Fixed in a872091
