### ISSUE TITLE
Change the wording on the Sync FastDL page

### ISSUE THREAD

**Issue by pedrotski** [wisp-gg/frontend#389]
### Describe the feature and why you would like to see it.

Make the wording on the FastDL page less game specific. game-specific

### Describe the solution you'd like.

This is the current text

This will sync all your FastDL content from the game server, compress it and upload to our web server. Everything inside the garrysmod/, garrysmod/addons/ and garrysmod/gamemodes/ folder that contains downloadable content will be synced.

Change it to 

This will sync all your FastDL content, including custom maps, models, materials, and more, from the game server. It will compress and upload the content to our web server.

**Comment by WISPdotGG** [comment]
Why do you think the information about the directories should be removed?
It's common on other panels for the fastdl sync to only sync content in the
root directory - ignoring the addons directory

**Comment by pedrotski** [comment]
Because the example of always gmod no matter the egg looks unpolished when it shows up for CSGO, CSS, Quake, Wolfenstein etc. 

The directory its actually syncing is also irrelevant and should be covered in the host's knowledge base anyway.
