### ISSUE TITLE
"Administrate" Button gone from client side.

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/frontend#39]
**Describe the bug**
The administrate button no longer exists in client area.
Admin area is also missing a button to return to the client area on that server.

**To Reproduce**
1. Click on a server
2. See error

**Expected behavior**
I expect to be able to see the "Administrate" button in the client area and a button in the admin area to return to the client area view for that server.

**Screenshots**
![image](https://user-images.githubusercontent.com/61161558/153761777-16cd8d43-d46e-4c66-a7ea-f0334774b181.png)

Desktop (please complete the following information):
OS: Windows 10
Browser: Chrome
Version: 98.0.4758.82

**Comment by hoshic** [comment]
https://gyazo.com/cbf7aa0f004d4010503ca8d97b10704e

![cbf7aa0f004d4010503ca8d97b10704e](https://user-images.githubusercontent.com/61242061/153762758-ff9c477a-819e-4055-88eb-27e7b706d45b.png)

**Comment by WISPdotGG** [comment]
The admin page button should just link to the page you're looking at. Instead of a second button being added.

**Comment by hoshic** [comment]
missing in the admin area aswell 

https://gyazo.com/5b9f6c73123d32543893deaec1acf3d8

**Comment by WISPdotGG** [comment]
> missing in the admin area aswell
> 
> https://gyazo.com/5b9f6c73123d32543893deaec1acf3d8

Yeah, I'll leave this issue open for both buttons & update your original post

**Comment by TrixterTheTux** [comment]
Should be fixed in next release.
