### ISSUE TITLE
Decompress using the panel

### ISSUE THREAD

**Issue by Larsdeijsbeer** [wisp-gg/frontend#390]
### Describe the bug

Decompressing large files (19gb) returns an error on the panel: Something went wrong while trying to perform this action.
I didn't get any logs on the daemon side.

### Expected Behavior

It should show a message like: "The file is being decompressed"

### Actual Behavior

Message: Something went wrong while trying to perform this action.

### Steps to Reproduce

Decompress a large file using the panel

### Browser Details

Chrome

### Operating System

Windows 11

**Comment by drizmans** [comment]
Closing in favour of https://github.com/wisp-gg/frontend/issues/308
