### ISSUE TITLE
Announcement Bar Option

### ISSUE THREAD

**Issue by joti-prime** [wisp-gg/frontend#404]
### Describe the feature and why you would like to see it.

Adding an announcement bar option would allow administrators to easily communicate important information to users.

### Describe the solution you'd like.

Add an option in the main dashboard to display an announcement bar at the top of the page, where administrators can enter and update announcements.

**Comment by Software-Noob** [comment]
The Panel already contains an announcement system, which utilizes the notification system. Whenever there's a new notification from any action, such as reinstalling or announcement, it'll show up there.

![image](https://github.com/wisp-gg/frontend/assets/10975908/466b29ab-44eb-4c9a-8f96-7fdc4447e5ad)

![image](https://github.com/wisp-gg/frontend/assets/10975908/04a6da89-46a8-4c7e-a2c5-eb4a60a3ebb8)

**Comment by joti-prime** [comment]
People don’t look a small icon at the bottom of the page, a good announcement must be show at the top in a bar format, and then give the option to choose if the user can close it or not. The actual one is like a normal notification system, and also doesn’t send an email to customers so is not the best one. There are a lot of pterodactyl addons that already exists I don’t know why wisp doesn’t implement this small things that are easy to do.

**Comment by Software-Noob** [comment]
Implemented in the next release
