### ISSUE TITLE
Multiple File Selection and Zipping

### ISSUE THREAD

**Issue by joti-prime** [wisp-gg/frontend#405]
### Describe the feature and why you would like to see it.

Allowing users to select and zip multiple files at once would make it easier and more efficient to manage their server files, especially when working with large numbers of files.

### Describe the solution you'd like.

Add a checkbox next to each file in the file manager, allowing users to select multiple files. Then add an option to zip the selected files into a single zip file, which can be downloaded or saved to the server. Additionally, provide an option to select all files in a directory with one click.

**Comment by Software-Noob** [comment]
You can already select multiple files and compress them. You can also select all files.

You can't select all files with a button. Feel free to open a new issue for that. Please do not add multiple things to a single Github issue as it makes it hard to track.
