### ISSUE TITLE
Rust Query Not Working

### ISSUE THREAD

**Issue by ThePlay3r** [wisp-gg/frontend#407]
### Describe the bug

After Rust update, which requires the game and query port to be different, the Wisp's query doesn't work correctly - it tries to query using the game server port, which no longer works.

### Expected Behavior

Wisp should query Rust servers using the Rust's query port, not the game port.

### Actual Behavior

Wisp queries Rust servers using game port, resulting in the query failing.

### Steps to Reproduce

1. Create Rust server
2. See that the queried port is wrong
3. See that players/maxplayers and other query details are unknown.

### Browser Details

Firefox 113.0b8 (64-bit)

### Operating System

Windows 11

**Comment by Software-Noob** [comment]
This has been fixed in the next daemon update. It'll utilize QUERY_PORT env variable from the server when present, which so far has been the standard for all eggs that have a separate query port. Default eggs will be updated in the near future to accommodate this change and others.
