### ISSUE TITLE
Server transfer does not work between two nodes.

### ISSUE THREAD

**Issue by pimenta1807** [wisp-gg/frontend#417]
### Describe the bug

Server transfer stuck before sending the backup to the new server

### Expected Behavior

Files are moved to the new server and the old one is deleted from the original node.

### Actual Behavior

Transfering the server `3004a8a4-31bf-470f-b9a2-ec3b93ca37db` from Node A > Node B causes the following behavior.
### Node A:
Backup is done.
![image](https://github.com/wisp-gg/frontend/assets/86393537/59ed31ac-39e9-478e-b836-5abe5c662886)

Nothing else.
Logs from Node A:
https://termbin.com/5arr

### Node B:
A fresh server is created and succefully installed.
Nothing else.

Logs from Node B:
https://termbin.com/rn3b

### Steps to Reproduce

An important point is that both servers are on the same LAN, more info below.

### Browser Details

Opera GX

### Operating System

Windows 11

### Optional additional information

Node A (192.168.0.190) is in the same LAN as the Node B(192.168.0.191)
Node B acts under a VPN (10.0.0.4)

At that point, the panel never updates the status.
While stucked, the server has allocations both from Node A and B
![image](https://github.com/wisp-gg/frontend/assets/86393537/b7a42fa3-3aba-49d2-b3e5-c5ab707de5dc)

**Comment by BalinGrant** [comment]
I've had this happen with nodes in entirely separate locations. It isn't necessarily LAN based.

**Comment by Software-Noob** [comment]
The logs have expired thus can't really confirm anything, please attach the logs directly to prevent them from being lost.

I don't see anything that would cause it to fail only in local network though. Feel free to open a new issue or contact us at help@wisp.gg with the logs. Chances are the backup simply failed or took too long.
