### ISSUE TITLE
Can't switch pages anywhere

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/frontend#42]
**Describe the bug**
On any page which has multiple pages:
- Client side
- Server page in Admin area
- User page in Admin area
- Eggs page in Admin area

**To Reproduce**
1. Go to a tab which has multiple pages
2. Try to switch page
3. See error

**Expected behavior**
I expect to be able to switch pages to view all users, servers, allocations, eggs, etc.

Desktop (please complete the following information):
OS: Windows 10
Browser: Chrome
Version: 98.0.4758.82

**Comment by WISPdotGG** [comment]
This issue is a duplicate of #3
