### ISSUE TITLE
Allow all extensions when setting up FastDL

### ISSUE THREAD

**Issue by 0xCiBeR** [wisp-gg/frontend#425]
### Describe the feature and why you would like to see it.

It would be nice to be able to use a wildcard when specifying extensions for FastDL. Currently you have to manually allow the extensions you want 1 by 1.
For some games, this would mean an impossible task as there are numerous file types, for example Multi Theft Auto.

### Describe the solution you'd like.

Allow wildcard for extensions when setting up FastDL.

**Comment by Software-Noob** [comment]
Has been implemented as a wildcard for extensions and will be available in the next daemon release

```
    "extensions": {
      "*": true,
      "png": true,
      "jpg": true,
    },
```
