### ISSUE TITLE
UI Scaling issues

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/frontend#43]
**Describe the bug**
UI doesn't scale properly with different resolutions.
For example in Admin -> Administration -> General

**To Reproduce**
1. Go to  Admin -> Administration -> General
2. See error

**Expected behavior**
I expect the UI to scale to different screen sizes

**Screenshots**
![image](https://user-images.githubusercontent.com/61161558/153762254-27e686e8-b857-4747-8bd2-4123cb06cf31.png)

Desktop (please complete the following information):
OS: Windows 10
Browser: Chrome
Version: 98.0.4758.82

**Comment by victiondev** [comment]
appears to already be fixed
