### ISSUE TITLE
Download Failure

### ISSUE THREAD

**Issue by OutlawMatt** [wisp-gg/frontend#432]
### Describe the bug

When in the control panel, regardless of the file format. When you click the download button the CP just opens a new tab but does not download the file.

### Expected Behavior

For the file to download to your local machine

### Actual Behavior

Opens a new tab and refreshes the page instead of downloading the file.

### Steps to Reproduce

Step 1 - Open your File Manager
Step 2 - Click the 3 dots to the right
Step 3 - Select Download

### Browser Details

Opera LVL 5 (core: 102.0.4880.117)

### Operating System

Windows 11

**Comment by Software-Noob** [comment]
This has been fixed
