### ISSUE TITLE
Error when updating branding panel logo to SVG

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/frontend#44]
**Describe the bug**
When trying to update my panel logo to a SVG logo the attached error appears

**To Reproduce**
1. Go to Admin -> Administration -> Branding
2. Click on Panel Logo
3. Set logo to an SVG

**Expected behavior**
I expect to be able to set the logo to an SVG

**Screenshots**
![image](https://user-images.githubusercontent.com/61161558/153762545-03e707d4-db14-4515-a3cf-8ae5214c1441.png)

Desktop (please complete the following information):
OS: Windows 10
Browser: Chrome
Version: 98.0.4758.82

**Comment by WISPdotGG** [comment]
Can you please provide a copy of the SVG you're trying to use? Thanks

**Comment by JouanDeag** [comment]
> Can you please provide a copy of the SVG you're trying to use? Thanks

https://swehosting.com/bluelogga.svg

**Comment by TrixterTheTux** [comment]
The SVG is greater than 250KB. The error message not being descriptive is tracked in #109.
