### ISSUE TITLE
Ping to panel server no longer appears

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/frontend#45]
**Describe the bug**
You are not able to view the ping to the panel server anymore

**To Reproduce**
1. Go to any page
2. See error

**Expected behavior**
I expect to be able to see the ping

**Screenshots**
![image](https://user-images.githubusercontent.com/61161558/153762627-76947b90-8155-4ccf-abae-561a1cc98128.png)

Desktop (please complete the following information):
OS: Windows 10
Browser: Chrome
Version: 98.0.4758.82

**Comment by JouanDeag** [comment]
> The time shown wasn't the ping to the panel, it was the time it took for the page to generate serverside. I'm pretty sure this doesn't happen serverside anymore, so this feature wouldn't make sense to exist anymore.

Makes sense. Could add the latency to the server instead as an enhancement

**Comment by TrixterTheTux** [comment]
I don't think this metric is useful in most cases as most actions depend purely on the game node and there's no need for this metric to be checked most of the time (and when needed, can be done with any browser's network tab).
