### ISSUE TITLE
Broken title on pages

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/frontend#49]
**Describe the bug**
Login page shows "navigation.login.index.title" instead of an actual title

**To Reproduce**
1. Go to login page
2. See error

**Expected behavior**
I expect to see a real title.

**Screenshots**
![image](https://user-images.githubusercontent.com/61161558/153764647-c6f7386e-d86a-45b0-be3e-784fa1b8e095.png)

Desktop (please complete the following information):
OS: Windows 10
Browser: Chrome
Version: 98.0.4758.82

**Comment by JouanDeag** [comment]
This shows up on other pages as well from time to time

**Comment by DarthShmev** [comment]
Yes, can't seem to replicate this but I have seem it happen once or twice.

**Comment by WISPdotGG** [comment]
All 404 pages seem to have a broken title

**Comment by DarthShmev** [comment]
> All 404 pages seem to have a broken title

Can’t replicate on mobile safari. 
![2DE0DF8B-F0D2-4F67-8B90-9945819C22A4](https://user-images.githubusercontent.com/34663790/154104958-f048b141-e2df-4929-bc89-96197c6b225b.jpeg)

**Comment by TrixterTheTux** [comment]
Fixed in https://github.com/wisp-gg/frontend/commit/592d9553749206021c78860c1ef1e567e0842dce.
