### ISSUE TITLE
Padding: Popout console & manage button on homepage

### ISSUE THREAD

**Issue by Thomas-DevArk** [wisp-gg/frontend#5]
**Describe the bug**
The Settings/ Manage Button's Icon is clipping the bottom border

**Expected behavior**
Added Padding

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://i.imgur.com/UiXEOkz.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Brave

**Comment by drizmans** [comment]
Fixed in b2ebe7e496cc2a0d609ce8896db62d840d42dc35
