### ISSUE TITLE
Request: Remove pagination from file manager

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/frontend#54]
**Describe the solution you'd like**
Have all files in a scrollable list

**Comment by hoshic** [comment]
would improve the work flow by a lot, its terrible to go through pages while working on a server

**Comment by TrixterTheTux** [comment]
The idea behind this is to prevent _thousands_ of files crashing the browser. I've recently bumped the per-page amount to 100. Does this seem more reasonable?

**Comment by hoshic** [comment]
CTRL+F just wont anymore be that useful but at some point its way better than before

**Comment by JouanDeag** [comment]
> The idea behind this is to prevent _thousands_ of files crashing the browser. I've recently bumped the per-page amount to 100. Does this seem more reasonable?
Seems more reasonable altough I think having the amount of per page files customizable would be better. You could even slap a warning label on the "All" option saying "This may crash your browser" or something like that.

**Comment by WISPdotGG** [comment]
Closing this in favor of #67
