### ISSUE TITLE
Details widget missing on navbar

### ISSUE THREAD

**Issue by HydraDevFR** [wisp-gg/frontend#57]
![image](https://user-images.githubusercontent.com/55934542/153766037-09467d64-5d6e-4556-8528-4701f05007d1.png)
![image](https://user-images.githubusercontent.com/55934542/153766049-e59bcd56-d57b-487c-ac96-f56b06389caf.png)

Google Chrome
Windows 10

**Comment by WISPdotGG** [comment]
I don't understand this issue - could you please elaborate?

**Comment by WISPdotGG** [comment]
I understand this issue now, apologies

**Comment by TrixterTheTux** [comment]
Is this still an issue? How can this be reproduced?

**Comment by victiondev** [comment]
Closing this as no one else has seemed to report it and reproduction steps (or an explanation of the issue) were given - re-open if you're still having this issue.
