### ISSUE TITLE
API Bug

### ISSUE THREAD

**Issue by bastienroussel** [wisp-gg/frontend#6]
**Describe the bug**
API return an error 404 and 500 when WHMCS try to deploy a new service.

**Expected behavior**
Error 404 and 500 on automatic deployement.

**Screenshots**

![image](https://user-images.githubusercontent.com/52447846/153759516-0d9f0875-a4cd-451d-a2ae-2ae679dad53d.png)

**Additional context**
WHMCS in last version.

**Comment by TrixterTheTux** [comment]
Should be fixed in next release.

**Comment by bastienroussel** [comment]
New error with API :
User is correctely created but WISP return an error 500 when a post request to create an new server :/

![image](https://user-images.githubusercontent.com/52447846/153765912-509b0c7c-3317-4b96-9f7b-dabeb4cb797f.png)

**Comment by TrixterTheTux** [comment]
Could you check if it's fixed now?

**Comment by WISPdotGG** [comment]
2 users confirmed its fixed
