### ISSUE TITLE
Disk/Memory different on different pages

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/frontend#60]
**Describe the bug**
Less total disk space is shown in server details compared to admin and index.

**To Reproduce**
1. Go to My Server -> System -> Server Details
2. See error

**Expected behavior**
I expect to see the same number everywhere

**Screenshots**
(Server Details Page)
![image](https://user-images.githubusercontent.com/61161558/153766183-e2bf53bd-a05e-41ef-b05f-816333bfeaa4.png)
(Index Page)
![image](https://user-images.githubusercontent.com/61161558/153766205-c77ae5f2-ac07-4911-82f4-7a42fcc6d6ab.png)

Desktop (please complete the following information):
OS: Windows 10
Browser: Chrome
Version: 98.0.4758.82

**Comment by WISPdotGG** [comment]
Pretty sure one is being calculated in MB and the other in Mb

**Comment by JouanDeag** [comment]
That should then be changed for consistency. In this case 512 is the correct number
