### ISSUE TITLE
Incorrect user/pass error shown before submission

### ISSUE THREAD

**Issue by bgbuddyboy** [wisp-gg/frontend#61]
**Describe the bug**
When filling login data (in my case LastPass on mobile and desktop) the invalid user/password error is shown before pressing login

**To Reproduce**
When logging in, use an extension/app to auto fill login details.
(Could be isolated to LastPass and may be reproducable through other means, does not happen in v1 or other sites)

**Expected behavior**
Only show error after submission

**Screenshots**
![Screenshot_20220214-010759.png](https://user-images.githubusercontent.com/57832237/153766291-d4b272a6-8033-47dc-973b-3a9e848e9693.png)

**Comment by bgbuddyboy** [comment]
Data was redacted for privacy.

**Comment by WISPdotGG** [comment]
Do you have autofill enabled for lastpass?

**Comment by bgbuddyboy** [comment]
No, that is when filling manually.

**Comment by DarthShmev** [comment]
Validation errors show up after un-focusing the form fields. Instead only validate on submit?

**Comment by bgbuddyboy** [comment]
> Validation errors show up after un-focusing the form fields. Instead only validate on submit?

That is a much nicer way to put it and is accurate.

**Comment by victiondev** [comment]
hopefully fixed in next update
