### ISSUE TITLE
Tooltip shows up when it shouldn't

### ISSUE THREAD

**Issue by BeepSterr** [wisp-gg/frontend#64]
**Describe the bug**
Tooltip "You need the `control - Run commands` permission" shows up for admins

**To Reproduce**
1. Go to a users server
2. Hover over the command bar
3. Observe the tooltip, Even thought you can still send commands

**Expected behavior**
The tooltip shouldn't appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/1830450/153766436-d501343e-6255-48ff-942d-2f23aed5d129.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Edge (Chromium)
 - Version 98.0.1108.50

**Comment by Larkify** [comment]
Additional Info: I had this happen to me with other UI elements such as the general tabs on the side.
