### ISSUE TITLE
Notifications UI 

### ISSUE THREAD

**Issue by hoshic** [wisp-gg/frontend#66]
**Describe the bug**
Notifications, theres a space between title and latest message.

**Screenshot**
![f78968a8cfcd9f29fced2b52b51007be](https://user-images.githubusercontent.com/61242061/153766762-5d34cc31-611d-4191-88ec-52620b5688a4.png)

**Comment by TrixterTheTux** [comment]
Unable to reproduce, assuming due to #93.
