### ISSUE TITLE
Audit logs 

### ISSUE THREAD

**Issue by bastienroussel** [wisp-gg/frontend#71]
**Describe the bug**
Audit logs stay empty.

**To Reproduce**
1. Go on a Server
2. Click on 'Audit Logs'
3. See nothing

**Expected behavior**
Actions on the server should be shown on this page.

**Screenshots**
![image](https://user-images.githubusercontent.com/52447846/153767747-5721bb76-2973-4f08-833c-f2183518cb7c.png)

**Comment by WISPdotGG** [comment]
Actions like restarting aren't supposed to show - but actions like creating a backup or adding a sub user should. Do those populate the audit logs for you? It seems to be showing for me

**Comment by JouanDeag** [comment]
Audit logs seem to work for me. Remember that they got cleared so old ones won't show
