### ISSUE TITLE
Mobile responsivity bad

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/frontend#72]
**Describe the bug**
Panel loads zoomed in. Nav menu also has a lot of empty space which should be removed

**To Reproduce**
1. Go to panel
2. See error

**Expected behavior**
I expect to load in with 100% zoom level as well as nav menu not taking up 70% of the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/61161558/153767878-9a7d9849-91b5-4b9b-9f5b-db7cfbf793bf.png)
![image](https://user-images.githubusercontent.com/61161558/153767867-ec9d27ba-dddb-4e2e-aaee-58b5f121d329.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - OS: Android 10
 - Browser Samsung Internet
 - Version: Unknown. Can fetch if needed.

**Comment by rowansc1** [comment]
+ Can reproduce on iPhone XS Max | IOS 15.2.1 | Safari & Chrome

**Comment by Lunaversitay** [comment]
#130 fixes "My Servers" responsiveness

**Comment by WISPdotGG** [comment]
Fixed in the above PR
