### ISSUE TITLE
Zooming/responsivity issue

### ISSUE THREAD

**Issue by WISPdotGG** [wisp-gg/frontend#77]
**Describe the bug**
on zoom in the page shifts around, not going back to how it originally was after zooming back out

**To Reproduce**
on 4k
on server page like on the console
zoom out and then back into where I was
the page shifts around, not going back to how it originally was
before: https://i.imgur.com/Fq4a79r.png
after: https://i.imgur.com/FvSDHLs.png (still on 100%)

**Expected behavior**
Page to look like it did before zooming

**Screenshots**
before: https://i.imgur.com/Fq4a79r.png
after: https://i.imgur.com/FvSDHLs.png (still on 100%)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version unknown

**Additional context**
Reported by QuackDuck#6610

**Comment by TrixterTheTux** [comment]
Should be already fixed.
