### ISSUE TITLE
Better audit logs when no logs yet

### ISSUE THREAD

**Issue by WISPdotGG** [wisp-gg/frontend#79]
**Is your feature request related to a problem? Please describe.**
Someone might think it looks like it's broke, but that's only minor

**Describe the solution you'd like**
A better page when there are no audit logs

**Additional context**
screenshot: https://user-images.githubusercontent.com/52447846/153767747-5721bb76-2973-4f08-833c-f2183518cb7c.png
Issue where someone thought it was broke #71

**Comment by DarthShmev** [comment]
Similar to #68 , same idea. Perhaps a better message in general for lists.
