### ISSUE TITLE
Page/Servers showing errors after inactivity

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/frontend#82]
**Describe the bug**
After being inactive on the page for a while all servers start to error and won't go back to online even with a refresh.
Clearing cache does not resolve the issue.
I managed to get it semi-working by clearing cookies and cache and refreshing but it breaks again after ~30 seconds

**To Reproduce**
1. Go to Home page
2. Wait for a while.

**Expected behavior**
I expect to be able to be AFK on the webpage and not have it break after.

**Screenshots**
![image](https://user-images.githubusercontent.com/61161558/153770284-69b8a652-f746-4625-8578-37eaa6091000.png)
![image](https://user-images.githubusercontent.com/61161558/153770436-21144a97-2233-46a9-92f2-5036dea204f6.png)
![image](https://user-images.githubusercontent.com/61161558/153770661-065e27a3-1966-48e9-8149-2ce2eba84642.png)

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Chrome
Version: 98.0.4758.82

**Comment by JouanDeag** [comment]
Update: Refreshing with CTRL + F5 sometimes fixes it for a while

**Comment by JouanDeag** [comment]
Related to #18 I would think

**Comment by ApeToe** [comment]
Also experiencing this with Brave

**Comment by TrixterTheTux** [comment]
Is this still an issue? I usually leave the index page in the background and have never experienced this.

**Comment by JouanDeag** [comment]
This seems to have been fixed with the recent fix for the websockets. Closing the issue.
