### ISSUE TITLE
Database creation issue

### ISSUE THREAD

**Issue by TICHosting** [wisp-gg/frontend#83]
Hi i cant create datababases
![image](https://user-images.githubusercontent.com/99585272/153770800-b798a322-36c9-4743-843d-dd73ac256a54.png)

**Comment by desperadisse** [comment]
Same error
But in connection from, i don't have number "100"

**Comment by larsjarred9** [comment]
+1

**Comment by TrixterTheTux** [comment]
I'm unable to reproduce this locally and on the production instance. Do you have anything in the console?

**Comment by bastienroussel** [comment]
I can comfirm this issue, in client and admin side :/

**Comment by bastienroussel** [comment]
Creation work now at client side but not in the admin side :/ and we cannot link database host to an node

**Comment by desperadisse** [comment]
> Creation work now at client side but not in the admin side :/ and we cannot link database host to an node

Exactly

**Comment by TrixterTheTux** [comment]
Closed in favor of #172 (as the original clientside issue this was referring to got fixed).
