### ISSUE TITLE
No allocations can be added in build configuration

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/frontend#85]
**Describe the bug**
No allocations can be added as secondary allocations to a game server

**To Reproduce**
1. Go to Admin/Management/Server
2. Click on Manage on any server
3. Click on Build Configuration
4. Try to add another allocation
5. See error

**Expected behavior**
I expect to be able to add another allocation to my servers

**Screenshots**
![image](https://user-images.githubusercontent.com/61161558/153771283-a9ade668-2ec5-46a1-8002-fafcc4329442.png)

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Chrome
Version: 98.0.4758.82

**Comment by WISPdotGG** [comment]
Possibly related to #88

**Comment by 0xCiBeR** [comment]
This is not an UI only issue. You can't create servers via API that have more than one allocation

**Comment by Szabolcs24** [comment]
I cant manage my server because of this sadly, my whole network is waiting. Please fix it asap!

**Comment by victiondev** [comment]
Should be fixed in latest release
