### ISSUE TITLE
Reinstate old admin /view route for WHMCS module

### ISSUE THREAD

**Issue by Lunaversitay** [wisp-gg/frontend#86]
**Describe the bug**
The WHMCS module currently directs to `panel.test/admin/servers/view/{id}` but the route was changed internally and the `/view` route was removed.

**To Reproduce**
1. Click on "Go to Service" in WHMCS
2. Get linked to `panel.test/admin/servers/view/{id}`

**Expected behavior**
The `/view` route should still exist because the WHMCS module redirects you to it when you click on "Go to Service"

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.
