### ISSUE TITLE
Button to go to server from admin page missing

### ISSUE THREAD

**Issue by Lunaversitay** [wisp-gg/frontend#87]
**Describe the bug**
The old external link icon button on the server admin page is missing, there's currently no way to get to the client page for servers via the admin page.

**To Reproduce**
1. View a server in the admin area
2. No button to visit server in the client area

**Expected behavior**
There should be a button to let you go to the server in the client area from the admin area.

**Screenshots**
Here's a scuffed image of what I mean lul

![](https://i.lunaversity.dev/firefox_7NussJD72Q.png)

**Comment by JouanDeag** [comment]
Would be a nice feature. +1

**Comment by DarthShmev** [comment]
See #39 for tracking this.

**Comment by JouanDeag** [comment]
> See #39 for tracking this.

This is the reverse of #39
