### ISSUE TITLE
Egg Searching | New Mod & Allocations

### ISSUE THREAD

**Issue by rowansc1** [wisp-gg/frontend#88]
**Describe the bug**
When searching for an egg, no results are found. This occurs no matter if text is present or not. 

**To Reproduce**
1. Go to Service Management
2. Click on Mods
3. Click on Create
4. Click on the EGG drop down 
5. View no results

**Expected behavior**
All eggs which exist on the system should be propagated into this field // filtered by the text input. 

**Screenshots**
![Fi1smir0tVELgJa6k2sq8z3Tgd4yoQ](https://user-images.githubusercontent.com/37227235/153772399-bb73eb7d-d904-40c1-a96d-08997bd5781a.png)
![f1UHYsrCziGuPcVkAZ3zhmggV3EDa0](https://user-images.githubusercontent.com/37227235/153772401-fc2d51dd-52f0-4ce3-a579-735633e3cbb7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version N/A

**Additional context**
N/A

**Comment by WISPdotGG** [comment]
Possibly related to #85

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.
