### ISSUE TITLE
server installation page

### ISSUE THREAD

**Issue by hoshic** [wisp-gg/frontend#89]
**Describe the bug**
The installing server installing message / page most of the times doesent get shown.

https://gyazo.com/5e0e340d60b69634cf9da14185852b40

**To Reproduce**
Install a server that takes some time to install like a source game server.
And then click on it / try to manage it while instsalling

**Comment by krenny** [comment]
![image](https://user-images.githubusercontent.com/77990771/153772700-ade0580c-9558-4034-b374-0b08f03baa3d.png)

**Comment by JouanDeag** [comment]
Reproduced

**Comment by glitchxst** [comment]
Reproduced - same thing on my end

**Comment by victiondev** [comment]
Pretty sure this has been since fixed in a previous release, this happened because the state pages were not enforced until you tried interacting with the server.
