### ISSUE TITLE
Startup Parameter tickables are broken

### ISSUE THREAD

**Issue by Lunaversitay** [wisp-gg/frontend#94]
**Describe the bug**
When attempting to tick or untick a startup parameter it refreshes the page and doesn't actually do anything.
Also apparently according to a couple of our clients when the ticks are activated instead of removing/adding the startup parameter it adds `1 or 0` see screenshot for more info.

**To Reproduce**
1. Go to startup parameters
2. Tick one of the tickables

**Expected behavior**
Should remove/add the startup parameter its' set to but instead either doesn't work or adds 0/1.

**Screenshots**
![](https://i.lunaversity.dev/Discord_bOcYNqbxIq.png)
![](https://cdn.discordapp.com/attachments/285727063552294912/942515536531709972/unknown.png)

**Comment by WISPdotGG** [comment]
> tickables should be fixed (you'll likely need to trigger rebuild for it to update)
