### ISSUE TITLE
An invalid namespace was provided for the websocket.

### ISSUE THREAD

**Issue by desperadisse** [wisp-gg/frontend#98]
**Describe the bug**
I can't administer a server without the following message appearing at the top of the page.

**To Reproduce**
1. Go to 'Server'
2. Choose 1 server

**Screenshots**
[https://zupimages.net/up/22/06/omn7.png](url)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Firefox]
 - Version [v2.0.23]

**Comment by WISPdotGG** [comment]
Does this still happen if you restart the daemon with "wisp restart" through ssh?

**Comment by desperadisse** [comment]
I just realized that this is an error during a wrong installation of the container. But it's impossible to reinstall the server

**Comment by hoshic** [comment]
it occures when creating a server, can confirm

**Comment by TrixterTheTux** [comment]
Invalid namespace is intended behavior, reinstallation is being tracked by #105
