### ISSUE TITLE
Error message behind prompt box

### ISSUE THREAD

**Issue by krenny** [wisp-gg/frontend#99]
**Describe the bug**
When trying to create a location with a name already in use an error will apear,however this error is behind the prompt box making it unreadable.

**To Reproduce**
1. Go to 'Management>Locations'(on admin view)
2. Click on 'Create'
3. use the same name as as one of your locations
4. Enter a description

**Expected behavior**
Error message should be on top of the prompt box

**Screenshots**
![grafik](https://user-images.githubusercontent.com/77990771/153778388-37c2a2a3-f7f9-47e2-98af-34e30396c523.png)

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.
